wolfSSL/wolfssh

- Makefile.am
These were missing in v0.2.0. They are included in the archives for the website.
> added a couple more missing files to the makefile

- src/misc.c
Change misc.c error to warning and exclude the misc.c code from being compiled. Most people include all .c files and by default inlining is allowed, which in turn causes an #error in misc.c and it must be excluded. Since we know its already been properly included there is no reason to throw error here. Instead, show warning and exclude code in .c file.
Copied from wolfSSL pull request #521.
> Update misc inline code

- examples/echoserver/echoserver.c
- examples/server/server.c
Copied change to err_sys() from wolfSSL. Cleaned up a static analysis issue. Also added the attribute noreturn to the function since it doesn't actually return.
> err_sys() static analysis issue

- examples/echoserver/echoserver.c
- src/internal.c
- src/ssh.c
- wolfssh/internal.h
- wolfssh/ssh.h
1. Add in tracking of the number of bytes encrypted and decrypted. Trigger a callback function if the highwater mark is reached in either direction.
2. Refactor the session key storage and use to make re-keying easier to implement.
3. Moved the context and session init and resource free functions from ssh.c to internal.c.
> Transfer Highwater Mark, Session Key Refactoring

- src/internal.c
- wolfssh/internal.h
1. Added parsing of the Global Request message. Will log the request name string.
2. Send global request failure response if reply is requested. (This was an issue with a particular SSH client.)
> Global Request Message

- configure.ac
- examples/echoserver/echoserver.c
- src/internal.c
- wolfssh/internal.h
- wolfssh/ssh.h
- wolfssh/version.h
Added support for using aes128-gcm as the data cipher and MAC. Used the OpenSSH-style implementation rather than the RFC 5647 implementation. They are the same after the KEX. During KEX, OpenSSH-style implicitly assumes the required MAC rather than negotiating the required MAC.
Also, added option to the echoserver so that it can run with a single incoming connection or with multiple incoming connections. Single connection to assist with memory testing.
> Add AES-GCM

- README.md
* Added ECDH Group Exchange with SHA2 hashing and curves nistp256, nistp384, and nistp521.
* Added ECDSA with SHA2 hashing and curves nistp256, nistp384, and nistp521.
* Added client support.
* Added an example client.
* Changed the echoserver to allow only one connection, but multiple connections are allowed with a command line option.
* Added option to echoserver to offer an ECC public key.
* Added a Visual Studio solution to build the library, examples, and tests.
* Other bug fixes and enhancements.
> wolfSSH v1.2.0

- src/log.c
- wolfssh/log.h
- wolfssh/ssh.h
1. Added a logging function that always works whether or not debugging is enabled.
2. Modified the WLOG macro to always be built in, but disables cleanly.
> Logging Update

- src/internal.c
- wolfssh/error.h
1. Renumbered a few error codes.
2. Added an error code for stream reading when the channel is closed during the read action.
> Channel Close

- examples/echoserver/echoserver.c
- src/internal.c
Fixes for scan-build warnings that showed up with:
```
$ clang --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```
> fixes for scan-build warnings

- src/internal.c
- src/ssh.c
- tests/unit.c
- wolfssh/error.h
- wolfssh/ssh.h
1. Add a unit test to check all error codes have strings.
2. Add public function to return the error string for an error code.
3. Fill in the missing error strings.
> Error Code Unit Test

- src/internal.c
Thanks @TimParrish for bringing this up. This pull request updates the names for SHA fixing an issue when compiling against wolfSSL built with --enable-all.
> update name for SHA

- src/internal.c
Fixes a scan-build warning that showed up on OSX with default ./configure:
```
src/internal.c:6882:13: warning: Access to field 'connectChannelId' results in a dereference of a null pointer (loaded from variable 'ssh')
switch (ssh->connectChannelId) {
^~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
> fix scanbuild warning in SendChannelRequest()

- wolfssh/certs_test.h
This PR fixes the license header spacing on wolfssh/certs_test.h so that our license replacement script picks it up correctly.
> fix spacing on certs_test.h license header

- examples/echoserver/echoserver.c
- tests/unit.c
1. In the echoserver, free the thread context before exiting app on error.
2. In the unit test, when checking the KDF, initialize the sizes to zero
and the pointers to NULL after freeing them.
> Scan Build Fixes

- src/internal.c
1. Fixed bug in DoKexDhGexGroup() where ret was initialized to an error.
2. The peer channel ID set during the connect needs to be saved for use later.
> Small Fixes

- configure.ac
- scripts/commit-tests.sh
1. Add enable options for "all" and "distro". all enables all options.
distro enables all and turns on both shared and static library builds.
2. Updated the commit-tests script to perform a check on enable-all as well.
3. Made a few syntactical changes to commit-tests.
> Enable All for Configure

- src/internal.c
- src/ssh.c
- src/wolfscp.c
- src/wolfsftp.c
- wolfssh/port.h
changes "FALL_THROUGH" to be "FALL_THROUGH;" matching wolfSSL and checks if FALL_THROUGH is already defined in gcc-7 case.
> gcc-7 build fall through warning

- src/internal.c
- src/ssh.c
- wolfssh/internal.h
wolfSSL and wolfSSH both have a function named SendBuffered() and they are both set to local visibility. There is at least one build configuration where both versions of the function are visible and the compile fails. Changing the name in wolfSSH to add the pseudonamespace prefix wolfSSH_, and also changed the name of the function to SendPacket() since it is used with two other functions with Packet in the name.
> Function Name Change

- examples/client/client.c
- examples/echoserver/echoserver.c
- examples/server/server.c
- examples/wolffwd/wolffwd.c
- wolfsftp/client/sftpclient.c
On a raspberry pi the default for "char" type is unsigned. i.e. -1 = 255. This changes the type in the examples to "int" for catching a -1 return value.
Fix for issue https://github.com/wolfSSL/wolfssh/issues/124
> use int type for getting example args

- src/port.c
ReadFile and WriteFile return non zero value on success. Also checks for EOF and returns 0 in that case.
> fix return check on ReadFile and WriteFile

- src/port.c
Change the ifdef around the Win32 wrapper functions to be switched off when SCP or SFTP aren't enabled on a windows build.
> Windows Build Fix

- examples/sftpclient/sftpclient.c
- ide/winvs/README.md
1. Update the Windows build README.
2. Add a guard to the sftpclient.c so it builds without SFTP enabled.
> Build Cleanup

- examples/client/client.c
- examples/portfwd/portfwd.c
- examples/sftpclient/sftpclient.c
- src/internal.c
- src/ssh.c
- wolfssh/error.h
- wolfssh/internal.h
- wolfssh/ssh.h
The public key check callback hook is given a pointer to the public key, the size of the key, and the application-specific context data.
1. Added a callback function hook for checking the public key sent to the client by the server. It defaults to accepting the key.
2. Added accessors for the public key check callback function and context data.
3. Added a dummy callback to all the example tools.
> Public Key Check Callback

- src/internal.c
- tests/api.c
- tests/include.am
1. Added API test for wolfSSH_CTX_UsePrivateKey_buffer().
2. Added the string->binary code to the API test.
3. Fixed a bug in UsePrivateKey(). When loading a new key into a CTX that already has a key, also reset useEcc.
4. Added a test case for wolfSSH_new() returning a null.
5. Fixed the automake include of AM_CPPFLAGS. Now the test tools can find the -D flags.
> Unit Testing - UsePrivateKey_buffer

- src/internal.c
- wolfssh/internal.h
1. PreparePacket() is to be given an estimated payloadSz, not the actual
payloadSz. The payloadSz should be larger or equal to the actual.
2. BuildPacket() calculates the actual payloadSz based on the position
of idx and value of idx stored before PreparePacket() returns. The size
of the padding is also calculated at this point.
Currently, everything going into a packet needs to be calculated ahead
of time and saved locally until the output buffer is prepared. This
requires saving RSA and ECDSA signatures in large buffers to be copied
later. Now such things can be calculated directly into the output buffer
without the temporary storage and copy.
> Refactor Packet Assembly

- src/internal.c
If certain variables are set to NULL a WS_BAD_ARGUMENT is set but there
is no return until the end of the function. In both the cases in this
commit the NULL ptr could be dereferenced after the ret has been set.
> Fix possible NULL ptr dereferences

- wolfssh/port.h
- wolfssh/visibility.h
This PR fixes two issues with building wolfSSH on Cygwin:
1.  FIONREAD was undefined, Cygwin defines it in <sys/socket.h> instead of <sys/ioctl.h>
2.  Visibility warnings.  Added a check for \_\_CYGWIN\_\_ in visibility.h and rearranged slightly.  These were fixed in wolfSSL proper with https://github.com/wolfSSL/wolfssl/pull/2253
> Fixes for Cygwin build

- src/internal.c
Fix a bug with the AES support. AES keys weren't set if only AES-CBC or AES-CTR were enabled. Changed the AND comparison to OR.
> AES Bug Fix

- examples/echoserver/echoserver.c
- src/internal.c
- src/ssh.c
- wolfssh/internal.h
- wolfssh/ssh.h
Response SSH_MSG_REQUEST_FAILURE to Keep-Alive. IETF:draft-ssh-global-requests
> MSGID_REQUEST_FAILURE to response MSGID_GLOBAL_REQUEST

- examples/echoserver/echoserver.c
- src/ssh.c
- src/wolfsftp.c
- wolfssh/ssh.h
1. When printing server worker errors, print out the error string on the stored error code, not the return value.
2. If the error is a socket error, don't try to send a shutdown message to the peer.
3. Update the echoserver to close the connection cleanly when the SFTP peer exits.
4. Added a function to check a WOLFSSL_CHANNEL if it is in eof.
> Echoserver Maintenance

- src/internal.c
- src/ssh.c
- wolfssh/error.h
1. Add new error WS_ERROR to replace WS_FATAL_ERROR.
2. Added error WS_SSH_NULL_E and WS_SSH_CTX_NULL_E for the error to string functions for when ssh is actually NULL.
> Error Code Maintenance

- examples/echoserver/echoserver.c
- src/internal.c
- src/ssh.c
The echoserver should not let someone try indefinitely to connect with bad passwords. The user authentication callback needs to keep track of that if desired and return a callback error code to reject the user. (This is an update to PR #198.)
> Password Failure Disconnection

- src/internal.c
- src/ssh.c
- wolfssh/error.h
Fix the error code for sending data on a channel that hasn't confirmed open yet to be an error code rather than a dummy value.
> Fix Error Code

- src/internal.c
- src/log.c
- src/port.c
- src/ssh.c
- src/wolfscp.c
- src/wolfsftp.c
- wolfssh/internal.h
- wolfssh/port.h
- wolfssh/settings.h
- wolfssh/ssh.h
This PR adds a port of wolfSSH and SFTP (client and server) to Freescale/NXP MQX 4.2 (Classic).  The compiler used for this port was IAR-EWARM 7.50.2.  Changes include:
- MQX 4.2 SFTP port
- Fix to loop bound on wolfSSH_oct2dec()
- Fix IAR-EWARM compiler warnings
MQX file system operations require that the file system handle be available in addition to the file handle or file name.  To assist in this, a new API has been added that applications running on MQX will need to use to set the general file system handle:
```
wolfSSH_SetFilesystemHandle()
```
NOTE: SCP has not been ported to MQX.
> SFTP port to MQX 4.2 (MQX/MFS/RTCS)

- examples/sftpclient/sftpclient.c
Attempt to make parsing the chmod command more robust for the SFTP client example.
> adjust example sftp client chmod command parsing

- scripts/get-put.test
At the script's startup, the existence of the echo server is checked. Its successful startup is checked by waiting for the ready file. The previous version worked on macOS, but not Cygwin or Ubuntu. This works on all three.
> fix get-put test so it will run on Linux and Cygwin

- src/wolfscp.c
- wolfssh/wolfscp.h
- fix for repeat call of scp with changed directory name (i.e. scp -r ./test jill@127.0.0.1:/test
- check on directory already existing for Nucleus port
- fixes for parsing scp command and nucleus port, parsing picking up part of file name as command (i.e scp ./file-test.txt jill@127.0.0.1:/)
> Fixes for SCP and SCP with Nucleus port

- src/internal.c
When fuzzing this, I noticed that AddressSanitizer will perform a ```strlen()``` on the arguments to ```WSTRNCMP```, which leads to an out-of-bounds read notification, as ```name``` is not null-terminated.
This might be seen as an invalid assumption on the part of AddressSanitizer, however despite the fact that ```strncmp``` allows setting a max. length parameter, it might assume the parameters to be null-terminated anyway. The specification of ```strncmp``` is ambiguous on this matter as far as I can tell; it takes two ```const char*``` arguments (which implies null-termination), but makes no mention of an explicit requirement for null-termination. In this light, the current use of ```WSTRNCMP``` might be undefined behavior.
Either way, this PR is required to make fuzzing without false …
> In NameToId, prevent any reliance on null-termination of string.

- src/internal.c
1. Before attempting to resize the output buffer in PreparePacket, make sure the length and index in the output buffer is consistent.
2. If SendPacket gets a general error back from the call to the transmit I/O callback, flush the output buffer and return the general error upstream.
> Maintenance: RX/TX

- examples/client/include.am
- examples/echoserver/include.am
- examples/server/include.am
- examples/sftpclient/include.am
Remove redundant items from the automake includes. They were including files already included.
> Automake Include Maintenance

- src/wolfsftp.c
draft followed for SFTP implementation states "However, clients SHOULD NOT attempt to parse the longname field for file attributes; they SHOULD use the attrs field instead." but in interop testing one peer is parsing the long name. This adjusts the long name so that it can be parsed....
> adjust long name

- examples/sftpclient/sftpclient.c
- src/internal.c
- src/ssh.c
- wolfssh/ssh.h
This is altering the callback behavior for peer authentication some. It sets the WS_UserAuthData.type to be a bit map of all supported types before it is passed to the user callback. The first time the user callback is called a password is requested by wolfSSH, if the user returns a fail case from that then a public key is requested. This process of calling requesting type individually is to not break previous use cases for the authentication callback.
> updates to auth callback

- examples/echoserver/echoserver.c
- src/ssh.c
ZD 9884
Fix for when testing scp against echoserver. This change makes the return value of scp client from OpenSSH return 0 on a successful transfer.
> exit channel in echoserver before sending disconnect

- wolfssh/port.h
Include header rtcs.h. It is missed if not using SCP.
> MQX Maintenance

- examples/sftpclient/sftpclient.c
- src/internal.c
- if tests/api.test finds the file .DS_Store then the /./ check was reading over the buffer
- fix for sftp auto get/put test not free'ing the name list
> free name list after done and fix clean_path

- ChangeLog.md
- configure.ac
- examples/client/client.c
- examples/sftpclient/sftpclient.c
- ide/winvs/user_settings.h
- src/wolfsftp.c
- wolfssh/version.h
- wolfssh/wolfscp.h
1. Updated versions, README, and ChangeLog.
2. A couple changes to the configure script.
> Release Rollup

- src/ssh.c
- src/wolfscp.c
1. When receiving the EOF from the client, wolfSCP should be shutting down the connection.
2. When shutting down the connection, don't send Disconnect. Instead send channel exit, then follow with close. This tells the client that the program exited cleanly.
> SCP Disconnect

- configure.ac
Removed an initialization of AR_FLAGS and let the libtool version happen. This makes Ubuntu builds recreatable.
> Revert Libool Config

- examples/echoserver/echoserver.c
- src/internal.c
- wolfssh/ssh.h
- wolfssh/test.h
1. Added a compile time option to allow None as an authentication type, mainly for testing.
2. Added a couple updates for VxWorks builds.
> Auth Type None

- configure.ac
- src/internal.c
wolfSSL v4.5.0 introduced a new function, `wc_ecc_set_rng()`, which is present when ECC_TIMING_RESISTANCE is enabled. Added a check to the configure script for that function, and disable calls to the function if it isn't present. This allows wolfSSH to build against older versions of wolfSSL.
> ECC Update for wolfSSL v4.5.0

- examples/echoserver/echoserver.c
- src/wolfscp.c
ZD 10787
Can be seen with scp -P 22222 test.txt jill@127.0.0.1:/path/to/spot && echo $?
This makes it so that scp is a graceful shutdown. Before scp complained when wolfSSH tried to close a already closed channel.
> graceful shutdown with scp interop

- src/internal.c
- src/ssh.c
When changing the functions SendChannelData() and SendChannelAdjustWindow() to use the self channel ID instead of the peer
channel ID, forgot to update a couple instances. The test case at the time had matching ID numbers for self and peer and happened to work.
> SendChannel fix

- examples/client/client.c
- examples/echoserver/echoserver.c
- examples/portfwd/portfwd.c
- examples/scpclient/scpclient.c
- examples/server/server.c
- src/internal.c
- src/ssh.c
- src/wolfscp.c
- wolfssh/port.h
- wolfssh/wolfscp.h
To test, compile wolfssl with --disable-filesystem, then compile wolfSSH with --enable-scp.
Run the example server: ./examples/server/server and send a file (will take up to 1024 bytes of the file) or try and get the file test.txt from the server.
> add callback and example for no file system with SCP

- ChangeLog.md
- README
- configure.ac
- examples/echoserver/echoserver.c
- src/wolfscp.c
1. Update the readme, changelog, and configure.ac for the new version.
2. Cleanup some errors from building the code with a C++ compiler as a part of the test.
> Release 1.4.5

- examples/client/client.c
- src/internal.c
- src/port.c
- src/ssh.c
- wolfssh/port.h
1. A couple places weren't passing the correct heap pointer to free. Normally this was ignored in the build because the WMALLOC macro left them out. Found using wolfCrypt memory logging.
2. Replaced the call to strdup() with wstrdup() that takes a heap and type parameter so sit may allocate a buffer with WMALLOC() and be freed correctly by WFREE().
3. Tweaked the client to use a preallocated buffer for the private key rather than letting ReadKey allocate one. (Another WFREE() heap/type issue.)
> Fix Memory

- examples/client/client.c
- examples/echoserver/echoserver.c
- examples/server/server.c
- examples/sftpclient/sftpclient.c
- src/agent.c
- src/internal.c
- src/keygen.c
- src/ssh.c
- tests/api.c
- wolfssh/internal.h
If options are disabled in wolfCrypt, they shouldn't be used in wolfSSH. Currently covers DH and RSA.
> Optional Builds

- src/internal.c
Added some additional bounds checking to some of the parameters in the public key user auth messages. There was a chance that an out of bounds buffer read could happen. (ZD 10997)
> User Authentication Bounds Checks

- src/internal.c
When filtering out the unknown names from name lists, the one that will be the client's guess KEX type can get removed if unknown. Let the first item in the client's list be added if unknown.
> KEX Packet Follows Fix

- src/internal.c
Check that the agent was set in the SSH session before trying to set its channel ID. (ZD 11099)
> Null Agent

- src/wolfscp.c
Resolves OSS-Fuzz issue 26413 (see ZD 11429)
> Call ParseBasePathHelper only after scpBasePath has been set

- src/internal.c
- wolfssh/wolfsftp.h
> adjust length for code standard

- wolfssh/port.h
For portability this is better. Example: Keil libc doesn't have `strdup `.
ZD 11320
> Use the internal version of `strdup `

- src/internal.c
1. Remove redundant 'FALL_THROUGH' from a switch-case.
> Release Cleanup

- examples/client/client.c
- src/agent.c
- src/internal.c
- wolfssh/agent.h
- wolfssh/internal.h
1. Add a command line option to client to allow agent use.
2. Some refactoring of the agent signing to make using ECDSA and RSA easier, and to add future methods.
3. Fewer public key singing attempts. (Only need one to know it isn't good.)
> Agent Updates

- configure.ac
- src/internal.c
This patch moves a few buffers from stack to heap when the option `WOLFSSH_SMALL_STACK` is defined.
A new configure flag `--enable-small-stack`, disabled by default, allows to select the option before building.
Loosely based on the suggestions submitted by Peter Sprenger in ZD 11472 for wolfSSH 1.4.4
> Added option for --enable-small-stack

- src/internal.c
Fixed broken configuration when compiling with `WOLFSSH_NO_DH`
This regression was introduced by PR #327
> Fix configuration WOLFSSH_NO_DH

- src/internal.c
On some systems (e.g. IMX-RT1060), a limited number of channels exist that can be used for crypto operations (sha256, aes128, ...).
wolfSSH should take into account the lifetime of these resources to avoid a descriptor leak.
This patch adds calls to destructors for the structure used during the handshake and throughout the ssh session.
> Fix descriptor leaks for sha/aes

- src/internal.c
When creating the handshake info, initialize the size of the e and x values to their sizes. To recreate issue:
wolfSSL: ./configure CPPFLAGS="-DFP_MAX_BITS=6144"
wolfSSH: ./configure CPPFLAGS="-DWOLFSSH_NO_ECDH"
> DH Size Fix

- examples/echoserver/echoserver.c
- examples/server/server.c
- src/internal.c
- tests/api.c
- wolfssh/internal.h
This fixes compiler errors in wolfSSH when wolfSSL is configured with `./configure --enable-ssh --disable-filesystem --disable-aesgcm --disable-ecc`
This issue was reported in https://www.wolfssl.com/forums/topic1711-does-wolfssh-require-aesgcm-and-ecc-and-nofilesystem.html
This PR updates and closes #328.
> Fix for NO_FILESYSTEM and WOLFSSH_NO_AES_GCM and !HAVE_ECC

- examples/client/client.c
- examples/echoserver/echoserver.c
- src/ssh.c
Loading and using created keys can now be done with:
```
ssh-keygen -t rsa -b 4096 -m PEM -f test.key
<convert test.key to DER format test.key.der>
./examples/echoserver/echoserver -j test.key.pub
./examples/client/client -i test.key.der -j test.key.pub -u <username from test.key.pub>
```
> make loading user created keys into the examples easier

- configure.ac
- examples/client/client.c
- examples/echoserver/echoserver.c
- examples/portfwd/portfwd.c
- examples/scpclient/scpclient.c
- examples/server/server.c
- examples/sftpclient/sftpclient.c
- src/internal.c
- src/port.c
- src/wolfsftp.c
- tests/api.c
- tests/sftp.c
- tests/testsuite.c
- tests/unit.c
1. Add include config.h to the example and test tool sources. They use some of the types from wolfCrypt's types.h and aren't finding them available. Also moved config.h to the top level source directory.
2. In the version of the system I was building for, functions pread() and pwrite() weren't readily available. Added a DECL check to configure to find if they are in unistd.h, and if not use the home brewed wPread() and wPwrite().
3. Cleaned up a bunch of compiler warnings for things like possible use of uninitialized variables and shadowing global names.
> Fixes when compiling with an old version of GCC

- src/wolfscp.c
The OSS-Fuzz detected a possible use of uninitialized data. Since it is text output for the STDERR of the peer, make sure the string is actually null terminated before fprintf to stderr.
> Fix SCP Extended Data Print

- src/wolfscp.c
When using a small file buffer for SCP, there was a combination of file size and channel window size where SCP would read the remainder of the file, close it, send a small message because the peer's window was full, then try reading the file again. The change keeps trying to send if the file buffer still has data. (ZD #13808)
> Small Buffer wolfSCP

- examples/echoserver/echoserver.c
- src/wolfsftp.c
1. The echoserver's sftp_worker() was treating the WS_CHAN_RXD status as an error and failing out. Updated to clear the error status.
2. wolfSSH_SFTP_read() was also treating WS_CHAN_RXD status as an error and terminating the transfer. Update to treat like the other status.
> SFTP Channel Receive Fix

- src/wolfscp.c
Simply don't read if file size is 0. 
Fixes ZD 13929
> Bugfix: erroring out on copying empty file

- configure.ac
- examples/echoserver/echoserver.c
- examples/scpclient/scpclient.c
- src/internal.c
- src/ssh.c
- src/wolfscp.c
- wolfssh/test.h
- wolfssh/version.h
* Fixes for cross-compiling (don't force library path references).
* Fix for FIPS 140-3 on ECC private key use.
* Fix for IPv6 with scpclient.
* Wrong macro for fall through.
* Add support for flushing file IO using `WOLFSCP_FLUSH`.
* Whitespace cleanups.
> Fixes for cross compiling with FIPS

- src/internal.c
- src/io.c
wolfSSH is translating the return code in wsEmbedRecv, but not in wsEmbedSend.  This is causing issues on MQX.  See ZD 14145.
> Translate return code in wsEmbedSend.

- ide/Espressif/ESP-IDF/default_espressif_options.h
- ide/Espressif/ESP-IDF/libs/CMakeLists.txt
- ide/Espressif/ESP-IDF/libs/component.mk
- ide/Espressif/ESP-IDF/setup.sh
- ide/Espressif/ESP-IDF/setup_win.bat
- ide/Espressif/ESP-IDF/wolfssh_espressif_semaphore.md
- ide/Espressif/README.md
initial [setup_win.bat](https://github.com/wolfSSL/wolfssh/compare/master...gojimmypi:ESP32_component?expand=1#diff-9dda2c0b133c2b0bcb2d5b28ac8d88d97b1aac3b803ed402dba0fe73a465d9dc) for the ESP-IDF `wolfssh` and a placeholder for `setup.sh`
> initial windows ESP-IDF wolfssh component setup

- ide/Espressif/ESP-IDF/setup.sh
- ide/Espressif/ESP-IDF/setup_win.bat
there's likely no functional difference, as Windows can handle missing, trailing quotes in a path. Still, the trailing quotes were missing and addressed in `f38832c`.
edit: also added minor feature revision to [setup_win.bat](https://github.com/gojimmypi/wolfssh/blob/02347c4eaa6df641db7d85cc6aad639f9b6f05c1/ide/Espressif/ESP-IDF/setup_win.bat#L1) for Windows, and implemented new line-by-line match in [setup.sh](https://github.com/gojimmypi/wolfssh/blob/02347c4eaa6df641db7d85cc6aad639f9b6f05c1/ide/Espressif/ESP-IDF/setup.sh#L1) for Linux
> Espressif component install; updated setup_win.bat, new setup.sh 

- wolfssh/settings.h
Improve detection of ECC RNG requirement when building without `./configure`. For reference this normally comes from the `configure.ac` here https://github.com/wolfSSL/wolfssh/blob/master/configure.ac#L126, however when building without configure this causes an issue with all ECC signing. If the ECC RNG is not set with `wc_ecc_set_rng` then it will result in an ECC signing error `MISSING_RNG_E`.
> Improve detection of ECC RNG requirement

- src/internal.c
For RSA user authentication, initialize the arrays used to store the check value and the signature before loading and comparing them. (ZD 14412)
> RSA Userauth Initialization

- ide/Espressif/ESP-IDF/libs/CMakeLists.txt
1. Update the list of files to leave out of the build. They are from wolfCrypt and aren't needed. Also left out wolfSSH's version of misc.c as it is handled automatically.
> ESP-IDF Build Cleanup

- src/internal.c
For ECC user authentication, initialize the mpints used to store the signature before checking it. (ZD 14412)
> ECC Userauth Initialization

- src/internal.c
This address an issue reported in ZD14507
> Fix mem init error in DoKexDhReply

- src/wolfsftp.c
We were only only showing the output of the first message of a directory listing
which is wrong. A directory listing can be composed of several messages so we
must keep reading until there is no more to read.
Fixes ZD14587
> Fixes directory listing output in sftp.

- examples/echoserver/echoserver.c
- src/internal.c
- src/io.c
- src/ssh.c
- src/wolfsftp.c
- wolfssh/wolfsftp.h
> handle files with . in name and fix for window resize want write case

- .gitignore
- apps/wolfsshd/configuration.c
- apps/wolfsshd/include.am
- apps/wolfsshd/test/test_configuration.c
- examples/portfwd/portfwd.c
- wolfssh/port.h
1. Fix the wildcard config file include.
2. Update the guard flags so macOS can also use wildcards.
3. Change the user priviledge separating setting to a bitfield.
4. Add test_configuration test to gitignore.
5. Process the included config files in strcmp order.
> wolfSSHd Wildcard Config Includes

- src/internal.c
1. Initialize a variable that might be used unset later.
> Old Compiler Warning Cleanup (GCC 4.0.2)

- src/internal.c
> never call mp_clear on something that hasn't been initialised.
The implementation in sp_int.c (as does integer.c) uses the 'used' field to determine the number of elements to zero out.
The tfm.c implementation just clears everything without reading values and so we may have got away with it in the past.
Fixes an issue from ZD14775
> Fix DoUserAuthRequestEccCert to only call mp_clear on vars that have been init'd

- src/internal.c
1. Fuzzing found a bad read when processing an X.509 certificate chain. Use the correct bounds when checking value reads.
2. Fix a potential NULL dereference with the ssh-agent. Move the check inside an everything-ok check.
3. Fix a couple dead writes.
(ZD 14803)
> Fuzzing and Scan Build Fixes

- examples/echoserver/echoserver.c
- src/internal.c
- src/ssh.c
- tests/api.c
- wolfssh/error.h
- wolfssh/internal.h
1. Allow user to add multiple server keys to the CTX up to a limit.
2. Clear the list of server's keys when releasing the CTX.
3. Update the API test case.
4. Server key algo list based on keys loaded.
5. Server uses key requested by client.
6. Change echoserver to load ECC and RSA key, -E option to select order.
7. Added a function to identify keys, and another to identify certs.
8. Added a function to add keys or certs to the list of keys and certs.
9. Fix return value for MAC Algo C2S match fail to the correct value.
> Multiple Server Keys

- apps/wolfsshd/include.am
- examples/client/include.am
- examples/echoserver/include.am
- examples/portfwd/include.am
- examples/scpclient/include.am
- examples/server/include.am
- examples/sftpclient/include.am
- tests/api.c
- tests/api.h
- tests/include.am
- tests/sftp.c
- tests/sftp.h
- tests/testsuite.c
- tests/testsuite.h
- tests/unit.c
- tests/unit.h
Make a few changes to the automake scripts used in the wolfSSH test and examples. Removed and consolidated some of the build control variables. Added some header files for the tests so they can be run in separate test applications.
> Automake Refactor

- src/internal.c
- src/io.c
- src/log.c
- src/ssh.c
- wolfssh/internal.h
1. Rename the type struct Buffer as struct WOLFSSH_BUFFER.
2. Rename the function Receive() as ReceiveData().
3. Fix unused variable value.
4. Rename the I/O callback functions LastError() as wsErrno() and TranslateReturnCode() as wsReturnCode(). LastError was conflicting with something, and TRC was just long.
5. The logFunction callback pointer isn't used in non-debug builds, and the compiler reported as such. Reference the variable to hush the warning.
> Fixing name conflicts with the RTOS Integrity

- examples/client/client.c
- examples/echoserver/echoserver.c
- examples/portfwd/portfwd.c
- examples/scpclient/scpclient.c
- tests/api.c
- tests/unit.c
- wolfssh/test.h
1. Deduplicate threading macros and typedefs where wolfCrypt has the default versions.
2. Add the user_settings.h/options.h include that is missing from examples.
3. Remove some dead code from the echoserver's user authentication function.
> Threading Deduplication

- tests/api.c
- tests/testsuite.c
- tests/unit.c
1. Remove the flag NO_MAIN_FUNCTION from the test tools.
2. For unit and api tests, follow the patter for the testsuite with its NO_TESTSUITE_MAIN_DRIVER check.
> Test Tools

- src/wolfsftp.c
- tests/api.c
- wolfssh/wolfsftp.h
1. Add some comments describing the constants WOLFSSH_MAX_SFTP_RW and WOLFSSH_MAX_SFTP_RECV.
2. When the server processor receives a request for file data during a file transfer, limit the amount of data sent to the client by the value WOLFSSH_MAX_SFTP_RW.
(ZD 13057)
> wolfSFTP Size Check

- src/agent.c
- src/internal.c
- wolfssh/internal.h
Refactoring to remove the need for mp_int types and any of the math functions from wolfCrypt. wolfCrypt provides APIs for generating and verifying signatures and for checking keys, use them. The functions were only used for ECDSA public keys and ECDSA X.509 certificates.
To test the X.509 certificates:
```
./configure --enable-certs CFLAGS=-DWOLFSSH_NO_FPKI && make
./examples/echoserver/echoserver -J fred:./keys/fred-cert.pem -j ./keys/fred-key.der -a ./keys/ca-cert-ecc.pem
./examples/client/client -u fred -i ./keys/fred-key.der -J ./keys/fred-cert.der -A ./keys/ca-cert-ecc.der
```
This should correct issue #413.
> Remove Public Math

- configure.ac
- examples/client/client.c
- examples/sftpclient/sftpclient.c
- src/internal.c
- src/ssh.c
- wolfssh/internal.h
Fixes verification of the host when using X509 certificates:
The following commands should print out the IP check of the hosts certificate on the client side (with it using X509). Without this PR it is not using certificates with the connection, which can be seen by changing the clients -A CA certificate and the connection still being established.
```
sudo ./apps/wolfsshd/wolfsshd -f sshd_config -D -d
./examples/client/client -i ./keys/fred-key.der -J ./keys/fred-cert.der -A ./keys/ca-cert-ecc.der
```
Adds X509 support to SFTP example client.
> fix for x509 use, add cert use to sftp client

- ChangeLog.md
- examples/sftpclient/sftpclient.c
- src/wolfsftp.c
1. There were a couple spots during a large file transfer where the client rekeying the session would interrupt the transfer and/or reset the amount of file data transfered. Fixed that with a check for WS_CHAN_RXD.
2. Added a build option to interrupt a file transfer after 2 minutes. Large files will take longer.
To recreate: generate a 2GB file. Use wolfsftp client to transfer the file from the echoserver. It should fail out after a while. When testing the PR, add the CFLAGS WOLFSSH_NO_SFTP_TIMEOUT.
> SFTP Large File Fix

- src/wolfsftp.c
- wolfssh/wolfsftp.h
Improve the througput of SFTP. Clients will request a particular size chunk of a file at a time. Most clients are flexible with receiving less than requested. But, sending 1kiB at a time requires many times more messages, encryptions, and transmits than when sending a larger block. One particular client requests 32kiB blocks, always, and expects to get 32kiB at a time. This changes the amount buffered to 32kiB. You can change the value smaller, but may have issues with some clients.
Testing using Windows on VmWare as the client and the echoserver running on the macOS host machine.
> SFTP Speed

- examples/sftpclient/sftpclient.c
- tests/sftp.c
Prints out "file size in bytes, file name" with SFTP client when doing "ls -s".
> add '-s' option to print file sizes with 'ls' command

- examples/sftpclient/sftpclient.c
- scripts/get-put.test
- src/wolfsftp.c
Current master will hang with SFTP get-put where the file does not exist.
This adds setting the ssh->error value and a test case.
> set ssh error in sftp status not ok state

- README.md
- examples/sftpclient/sftpclient.c
- src/ssh.c
- wolfssh/internal.h
SFTP Stall Fix
1. Fixed issue where a SFTP connection would stall while upload a large file.
2. Remove a little duplicate code.
3. Increased the channel receive buffer size to 128k.
4. Fixed the max packet size to 32k.
5. Clear the error register when calling stream read.
To test: Enable SFTP. Start the echoserver. Connect to the echoserver with WinSCP. Upload a 1GB file to the echoserver. If you back out the size change commit, it should stall while uploading. (The size change commit improves throughput.)
(ZD 14607)
> SFTP Stall Fix

- src/internal.c
- wolfssh/internal.h
1. Fix the spelling on one of the feature disable guards.
2. Add a guard check to disable all things SHA-1.
> Guard Spelling

- examples/client/client.c
- examples/sftpclient/sftpclient.c
Gate use of `IPOverride` with `#if defined(OPENSSL_ALL) || defined(WOLFSSL_IP_ALT_NAME)`
Fixes #501
> Fix build error in client_test

- apps/wolfsshd/auth.c
1. Checking the string returned from crypt() to make sure it isn't a "*".
2. Checking the lengths of the strings when checking the password.
Testing:
```
./configure --enable-sshd --enable-sftp --with-wolfssl=<path>
make
cd apps/wolfsshd
touch sshd_config
sudo ./wolfsshd -p 22222 -h <path-to>/wolfssh/keys/server-key-ecc.pem -f ./sshd_config
sudo adduser --diabled-password foo
ssh -p 22222 foo@localhost
<enter random, should fail>
sudo passwd foo
<set a password>
ssh -p 22222 foo@local
<enter random, should fail>
ssh -p 22222 foo@local
<enter password, should login, logout>
sudo passwd -l foo
ssh -p 22222 foo@localhost
<enter password, should fail>
```
> wolfSSHd Shadow Fix

- README.md
- src/internal.c
- src/ssh.c
- wolfssh/internal.h
The implementation now complies with the following draft: 
https://www.ietf.org/id/draft-kampanakis-curdle-ssh-pq-ke-01.html
We implement the method as defined by the following name in that draft: 
ecdh-nistp256-kyber-512r3-sha256-d00@openquantumsafe.org
> ecc_p256-kyber_level1 interop with OQS OpenSSH

- examples/client/client.c
Before when connected to shell and hitting 'enter' the terminal would not update.
> add cr for enter with shell connections to windows server

- apps/wolfsshd/wolfsshd.c
On QNX chdir("/") could have issues at lower permission levels.
Note that not having the permission required for chdir stops the wolfSSH daemon from starting up.
> keep raised permissions for startup

- apps/wolfsshd/wolfsshd.c
The setuid/setgid of raise/lower permissions function was interfering with getgroupslist/setgroupslist. This places the group set function call earlier on.
> fix for setting secondary groups

- apps/wolfsshd/auth.c
Fix for sshd_config option `PermitEmptyPasswords yes`
> fix empty password support regression

- apps/wolfsshd/auth.c
Put macro wrapper around function getgrouplist(). The mac is treating it as taking a pointer to int rather than gid_t. Wrapper juggles that.
> Mac Build Fix

- src/internal.c
- wolfssh/error.h
- wolfssh/internal.h
Add user authentication support for RSA signing with SHA2-256 and SHA2-512.
The test I used to check the user authentication:
`./configure --enable-sftp CPPFLAGS=-DWOLFSSH_NO_SSH_RSA_SHA1 --enable-debug`
I like using SFTP to test the authentication. The flag **WOLFSSH_NO_SSH_RSA_SHA1** will disable the old and broken _ssh-rsa_ signature type. (The keys are still considered _ssh-rsa_ keys.) I used the wolfsftp example command:
`./examples/sftpclient/wolfsftp -u john -h localhost -p 22 -i ~/priv.der -j ~/pub.txt`
The keys _priv.der_ and _pub.txt_ are just for this test:
```
openssl genrsa -out priv.pem 2048
openssl rsa -in priv.pem -outform der -out priv.der
ssh-keygen -y -f priv.pem >pub.txt
cp ~/.ssh/authorized_keys ~/.ssh/authorized_keys.backup
cat ~/.ssh/authorized_keys.backup pub.txt …
```
> RFC 8332: Part 2

- examples/client/client.c
- examples/echoserver/echoserver.c
Reported directly to me. When building with WOLFSSH_SHELL on Windows the client project currently fails. This adds a macro guard around the include that is not found.
> fix for building client on windows with shell support

- examples/sftpclient/sftpclient.c
Reported by direct email. When using the sftp example and connecting to a windows machine the autopilot mode does not respect absolute paths passed in.
> check on absolute path from Linux to Windows machine

- src/internal.c
Simply return a string representation of WS_SUCCESS too.
> Convert WS_SUCCESS to string.

- src/internal.c
- src/wolfsftp.c
Reported via direct email. On Windows the high offset was not getting set with SFTP leading to not stopping when writing files larger than max word32 size (over 4G). When fixing that I also changed the assign function to not depend on overflow (undefined behavior) for incrementing the high offset value.
> fix file offest on Windows and change offset increment

- src/internal.c
- wolfssh/internal.h
Currently the implementation doesn't support having session channels coexist with other channels (including other sessions channels themselves), hence administratively forbid opening the channel in case such a situation arises.
> Correctly send out the CHANNEL_OPEN_FAIL message on failure.

- src/internal.c
1. Fixed used of a local variable whose name had changed and wasn't updated.
2. Added typecast to a 64-bit value that is added to a 32-bit value and stored as a 32-bit value for the kem size.
> OQS Cleanup

- autogen.sh
1. Remove redundant things from autogen.sh.
2. export the warnings variable to autoreconf sees it.
3. Simplify linking the configure hook script.
> Autogen Tweak

- apps/wolfsshd/auth.c
- apps/wolfsshd/configuration.c
- apps/wolfsshd/wolfsshd.c
- src/wolfscp.c
1. Fix missing updates to wolfSSHd.
2. Fix missing update to scp.
> WMACRO Update

- examples/client/client.c
When the example client is using non-blocking sockets, sometimes they don't block. The monitor thread on the socket wasn't handling WS_WANT_READ explicitly, and treated it as a fatal error. It should be reset to WS_SUCCESS.
> Nonblock Client Login Failure

- examples/client/client.c
1. Add quit parameter to the example client's thread_args structure. This will be used to let the windowMonitor thread know the application is quitting.
2. If the windowMonitor's quit flag is set, it will exit and not call wait again.
3. Join the windowMonitor thread rather than cancel it.
> Semaphores

- src/internal.c
Change sizeof a pointer to a string to WSTRLEN(). It was only copying part of the string "window-change" to the channel status message.
> Fix Terminal Window Size Update

- src/ssh.c
- wolfssh/ssh.h
1. Update wolfSSH_ReadKey_buffer() to decode PEM keys.
2. Add detection of PEM files to wolfSSH_ReadKey_file().
3. Add parameter labels to the prototypes of the ReadKey functions.
Test Cases
----------
```
$ ./configure && make
$ ./examples/echoserver/echoserver -e
$ ./examples/client/client -u hansel -i keys/hansel-key-ecc.der -j keys/hansel-key-ecc.pub
$ ./examples/client/client -u hansel -i keys/hansel-key-ecc.pem -j keys/hansel-key-ecc.pub
$ ./examples/echoserver/echoserver
$ ./examples/client/client -u hansel -i keys/hansel-key-rsa.der -j keys/hansel-key-rsa.pub
$ ./examples/client/client -u hansel -i keys/hansel-key-rsa.pem -j keys/hansel-key-rsa.pub
```
> Read PEM Keys

- configure.ac
- src/internal.c
1. Changed gathering the PTY window size from being OS dependent to availability of ioctl.h so both Linux and MacOS would start with the correct size.
2. Added a check to configure for sys/ioctl.h.
3. Changed GetTerminalSize() so it returns the pix width and height as well.
Test Case
---------
```
% echo $COLUMNS
% echo $LINES
% ./examples/client/client -t -p 22 -u user -i private-key -j public-key
% echo $COLUMNS
% echo $LINES
```
Without the change, on the macOS terminal, when you connect to the localhost server, the columns and lines will be 80x24. With the change, the columns and lines will match whatever your window is set to. (Mac would update correctly on window size change.)
> Initial PTY Window Size

- examples/client/client.c
- src/internal.c
- wolfssh/internal.h
1. Change GetTerminalSize() to GetTerminalInfo().
2. Add the term variable to the things GetTerminalInfo() looks up.
3. Return the actual value of the environment variable TERM to the server. If one isn't present, default to "xterm".
4. Clean up the whitespace in SendChannelTerminalRequest().
Misc other changes:
1. Cleanup whitespace in the recently added function SendChannelOpenFail().
2. Add labels to the parameters in the prototype for SendChannelOpenFail().
3. Remove the CR addition for Windows in the example client. Causes the enter key to double-strike.
Testing
-------
```
% echo $TERM
% ./examples/client/client -u username -i ~/.ssh/id_ecdsa -j ~/.ssh/id_ecdsa.pub -p 22 -t -h server
% echo $TERM
```
The TERM values should match. Before the change, the server will always be told …
> Term Update

- src/internal.c
Required for https://github.com/wolfSSL/wolfssh/issues/588, this PR addresses some minor issues where the Espressif compiler using cmake complained as shown below.
See the wolfSSH preview component: https://components-staging.espressif.com/components/gojimmypi/mywolfssh
Test drive the template example:
```bash
export WRK_IDF_PATH=/mnt/c/SysGCC/esp32/esp-idf/v5.1
echo "Run export.sh from ${WRK_IDF_PATH}"
. ${WRK_IDF_PATH}/export.sh
idf.py create-project-from-example "gojimmypi/mywolfssh^1.0.5-test:wolfssh_template"
cd wolfssh_template
idf.py build
```
If these errors are observed, the wolfssl`user_settings.h` needs to be adjusted by adding `#define WOLFSSH_TERM`:
```text
C:/test/mqtest/6/wolfssh_template/managed_components/gojimmypi__mywolfssh/src/ssh.c:1344:8: error: 'WOLFSSH' has no …
```
> internal.c var initialization for Espressif Component Manager 

- wolfssh/test.h
The minor PR adds some `#elif defined(WOLFSSL_ESPIDF)` sections to [wolfssh/test.h](https://github.com/wolfSSL/wolfssh/blob/master/wolfssh/test.h) that will be used by examples I have in the works for the Espressif ESP Component Registry at [components.espressif.com](https://components.espressif.com/components/wolfssl/wolfssl) as related to https://github.com/wolfSSL/wolfssh/issues/588.
My WIP is on the [staging site](https://components-staging.espressif.com/components/gojimmypi/mywolfssh?language=en) and the example of interest is [wolfssh_server](https://github.com/gojimmypi/wolfssh/tree/component-manager/ide/Espressif/ESP-IDF/examples/wolfssh_server).
> add WOLFSSL_ESPIDF Espressif sections in test.h

- wolfssh/test.h
1. The wolfSSL version number to check for the old threading code was v5.5.2, not v5.5.1.
2. A new wrapper was introduced around return for threading in what will be wolfSSL v5.6.4. Added that wrapper if it didn't exist.
3. Some other types for threading are added in v5.6.4, wolfSSH needs to use the old threading model if using wolfSSL v5.6.3.
Testing configuration:
./configure && make
Built wolfSSH against wolfSSL v5.5.0, v5.5.1, v5.6.3, and a modified version of the master branch with the version changed to v5.6.4.
> Threading Fix

- configure.ac
Add checks to configure.ac for the types __uint128_t, size_t, uint8_t, and uintptr_t. (Fixes issue #594.)
> Configure Type Checking

- examples/echoserver/echoserver.c
A couple changes to keep the echoserver from spin-locking. (Should fix #607.)
1. The SFTP worker should wait for data if the channel window is full. If the client isn't sending a window adjust, it might be because of a human time scale issue. New timeout is 60 seconds.
2. When the echoserver is waiting for something from the user and the select times out, wait a second instead.
> Echoserver Select Timeouts

- src/internal.c
This PR is to address the issue reported in ZD#16867.
This issue occurs because the index value, which is initialized to point to the signature part of the data, is pointing after the signature part, resulting in a buffer error(-1004). This index value must be initialized correctly.
This failure occurs when the server host key algorithm is RSA.
How to reproduce the issue:
1. configure wolfSSH with following options
./configure --enable-debug --enable-sftp CFLAGS="-DWOLFSSH_YES_SSH_RSA_SHA1"
2. comment out ID_ECDSA_SHA2_NISTP256 entry from cannedKeyAlgoClient[].
This is to ensure that only rsa-sha2-256 and ssh-rsa are listed in the Server-host-key algorithm list. The 　　WOLFSSH_NO_ECDSA macro could not be used because it would generate a build error.
4. build and run echoserver as a sever …
> Fix index of signature part in case of RSA

- apps/wolfssh/common.c
- wolfssh/port.h
Added Known Hosts file checking for the wolfssh application. It currently checks the file "~/.ssh/known_hosts". Reports missing, duplicate, or bad keys.
> Known Hosts

- src/agent.c
- src/internal.c
1. Moved the heap variable declaration to the top of the function
ChannelUpdateForward().
2. Only set heap if channel is non-null.
3. Tag heap as unused. Depending on the build environment, it might be
left out by the preprocessor.
4. Fix a bad memory type name used in a malloc in the agent.
5. Fix a use of heap when ctx->heap was intended.
6. Fix a typo where ssh->ctx->heap was intended.
> Unused Heap

- apps/wolfsshd/wolfsshd.c
ZD17083
Can be seen when running wolfsshd in the foreground, completing a shell connection and exiting, then viewing the process list.
> avoid zombie processes

- src/wolfsftp.c
Made setting file modes portable, by means of defining the WOLFSSH_SFTP_SETMODE and WOLFSSH_SFTP_SETMODEHANDLE macros, in which case the functions SFTP_SetMode and SFTP_SetModeHandle will have to be externally defined for the platform the library is being ported to.
> Made setting file modes portable

- src/agent.c
- src/internal.c
- wolfssh/internal.h
1. Added function wolfSSH_RsaVerify() which verifies the provided RSA signature with the provided key.
2. Call wolfSSH_RsaVerify() after all calls to wc_RsaSSL_Sign().
3. Changed a comparison between an unsigned and 0 to == from <=.
This fixes a potential but unconfirmed vulnerability in wolfSSH described in the paper "Passive SSH Key Compromise via Lattices" by Keegan Ryan, et al, at UCSD.
> RSA Verify Check

- ChangeLog.md
- README.md
- apps/wolfsshd/configuration.c
- configure.ac
- examples/sftpclient/sftpclient.c
- src/wolfsftp.c
- wolfssh/version.h
The usual updates and fixes for the release of v1.4.15.
> Release v1.4.15

- ChangeLog.md
- apps/wolfsshd/auth.c
1. Added a UNICODE define to the Windows build of the wolfSSHd auth module so it picked the correct strings.
2. Fixed a typo in the ChangeLog.
> Release v1.4.15: Last Second Fixes

- examples/echoserver/echoserver.c
- tests/api.c
- tests/sftp.c
- tests/testsuite.c
- wolfssh/test.h
There is a frequent intermittent failure with the Zephyr test. Added a 300ms timeout to the client after waiting for the server ready semaphore, seems to let the server get ready in the failure case for the client to connect.
Made a few changes to clean up the test a little.
> SFTP Test Maintenance

- apps/wolfsshd/test/sshd_term_size_test.sh
- apps/wolfsshd/wolfsshd.c
- src/internal.c
- wolfssh/internal.h
- wolfssh/ssh.h
Some cleanups and improvements to the code in wolfSSHd that starts the user's shell. Uses the modes in the client's terminal settings provided in the PTY request. Also configures some of the inherited variables in the new shell.
> wolfSSHd Terminal

- .gitignore
Add some commonly-ignored files & directories to the `.gitignore` file.
> wolfssh .gitignore update; VS / VS Code / CMake / Build

- src/ssh.c
The `PrivBeginPrefix` and `PrivSuffix` are only [used](https://github.com/wolfSSL/wolfssh/blob/60a29602e5893fd4e2ca0f4b6e2e05c6324154ed/src/ssh.c#L1835) in `wolfSSH_ReadKey_file()` which is [gated](https://github.com/wolfSSL/wolfssh/blob/60a29602e5893fd4e2ca0f4b6e2e05c6324154ed/src/ssh.c#L1770) with:
```
#if !defined(NO_FILESYSTEM) && !defined(WOLFSSH_USER_FILESYSTEM)
```
... thus otherwise there's a compiler warning about them not being used on a no-filesystem target.
There's also a `typeSz = 0` initialization that was failing as the Espressif compiler was complaining it was not initialized.
* Edit: see https://github.com/wolfSSL/wolfssh/issues/633
> Gate PrivBeginPrefix/PrivSuffix; init typeSz in ssh.c

- src/internal.c
`GetOpenSshKeyRsa()` is not used with `#define WOLFSSH_NO_RSA` and thus the compiler complains it is unused when RSA is disabled.
> Gate GetOpenSshKeyRsa with WOLFSSH_NO_RSA

- src/misc.c
As noted in https://github.com/wolfSSL/wolfssh/issues/633,  when building with the Espressif ESP-IDF, and the `misc.c` is not excluded in the `CMakeLists.txt`, I see this message:
```
[2/9] Building C object esp-idf/wolfssh/CMakeFiles/__idf_wolfssh.dir/C_/workspace/wolfssh-gojimmypi/src/misc.c.obj
C:/workspace/wolfssh-gojimmypi/src/misc.c:76:10: warning: #warning MISC_WARNING [-Wcpp]
76 |         #warning MISC_WARNING
|          ^~~~~~~
```
In particular, note the `MISC_WARNING` was previously defined as a descriptive string, but that string is not displayed at compile time.
This PR adds some macro logic to detect if `_Pragma` is supported, and if so the contents of `MISC_WARNING` is string-ified and displayed as appropriate.
Although this might have been simplified by simply using the …
> Improved "misc.c does not need to be compiled" message

- autogen.sh
Similar to https://github.com/wolfSSL/wolfssl/pull/6798 this PR fixes https://github.com/wolfSSL/wolfssh/issues/592 and prevents [autogen.sh](https://github.com/wolfSSL/wolfssh/blob/master/autogen.sh) from copying git hook shell scripts in WSL when the underlying file system is shared with Windows.
The wolfssh `autogen.sh` is slightly different from the wolfssl version in that only the `pre-commit.sh` file is used. This PR includes code that is commented out for future use of the `pre-push.sh`.
> no WSL/Windows git hooks from autogen.sh

- tests/sftp.c
- zephyr/samples/tests/tests.c
Modify the SFTP tests to use the file configure.ac instead of configure. Some environments do not have or use configure. Configure.ac is in the source archive.
> SFTP Test File

- src/internal.c
- src/ssh.c
- src/wolfsftp.c
- wolfssh/port.h
1. Nucleus builds changed the source file names to have a wolfssh_ prefix. Take that into account for misc.c.
2. Change CleanPath to add a delimiter to the input string.
3. Reorganize the WS_GETtime macros to clean up adding specific items for Nucleus.
4. Add some typecasting on some sizeof.
5. Some whitespace cleanup, and removing a redundant include.
(ZD: 14607, 16671, 16791, 17236)
> Nucleus Patch

- .github/workflows/sshd-test.yml
- .github/workflows/zephyr.yml
- apps/wolfssh/wolfssh.c
- apps/wolfsshd/auth.c
- apps/wolfsshd/test/create_sshd_config.sh
- apps/wolfsshd/test/run_all_sshd_tests.sh
- apps/wolfsshd/test/sshd_x509_test.sh
- apps/wolfsshd/wolfsshd.c
- examples/client/common.c
- keys/renewcerts.sh
- src/internal.c
- src/ssh.c
- tests/api.c
- wolfssh/internal.h
- wolfssh/ssh.h
- zephyr/samples/tests/sample.yaml
redirects stderr to extended data packets when sending them
> add piping of stderr

- examples/client/common.c
- examples/sftpclient/sftpclient.c
- src/internal.c
- tests/api.c
- wolfssh/internal.h
Fix WOLFSSH_NO_RSA case
wolfssl
$ ./configure --enable-ssh --enable-rsa=no
wolfssh
$ ./configure --with-wolfssl=/usr/local/ CFLAGS="-DWOLFSSH_NO_RSA"
> fix WOLFSSH_NO_RSA

- src/internal.c
Switch from wc_RsaSSL_VerifyInline() to wc_RsaSSL_Verify(). Fixes a bad free.
To reproduce:
./configure && make clean && make
./examples/client/client -u john -h localhost -p 22 -i ~/.ssh/id_rsa -j ~/.ssh/id_rsa.pub -t
I used my own RSA private key to log into the sshd locally on both my Mac and my Linux PC. Both crashed out with a bad free.
(ZD17381)
> RSA Verify Fix

- .github/workflows/windows-check.yml
Adding test case to try and avoid regression of this fix (https://github.com/wolfSSL/wolfssh/pull/653).
> add windows github action build test

- apps/wolfsshd/wolfsshd.c
In the case where the process started up and exited but did not close the other end of the pipe these last reads to clear out the stdout/stderr pipe could hang before. ZD17392
> set pipes as non blocking before last read

- .github/workflows/sshd-test.yml
- apps/wolfsshd/test/run_all_sshd_tests.sh
- apps/wolfsshd/test/sshd_large_sftp_test.sh
- src/internal.c
> Fix for large file transfers on client side with SFTP

- configure.ac
- examples/client/client.c
- src/internal.c
- wolfssh/version.h
> dev bundle, version 1.4.16

- src/internal.c
- src/ssh.c
- tests/api.c
- wolfssh/internal.h
- wolfssh/ssh.h
1. Add APIs to change the cipher lists used in the KEX init messages.
2. Add APIs to query the possible built in algorithms.
3. Reinstate the SHA-1 algorithm, but soft-disable it. It isn't offered by default but the user can set it for use.
(ZD 17568, Issue #659)
> Cipher List Configuration

- examples/client/client.c
- examples/echoserver/echoserver.c
Was using this example addition when testing https://github.com/wolfSSL/wolfssh/pull/661
> example set key algos

- src/wolfscp.c
1. Add a mask for the POSIX file modes.
2. Mask out the file mode bits when setting the C or D command for SCP.
(ZD 17562)
> SCP File Modes

- apps/wolfssh/wolfssh.c
- examples/client/client.c
ZD17595
Previously if setting a Windows terminal to "Windows Console Host", running the client.exe application and connecting to wolfSSHd (also running on Windows) the virtual terminal control sequences were not all handled well. Leading to the cursor jumping around in the terminal. This change makes use of Windows processing of virtual terminal control sequences instead.
> Use ENABLE_VIRTUAL_TERMINAL_PROCESSING on Windows treminal

- src/internal.c
1. Add dynamic memory type of string to the allocation of the list of modes when opening a pty.
2. When freeing a WOLFSSH object, free modes when it is set.
Testing using valgrind.
> Fix Modes Leak

- src/internal.c
- wolfssh/error.h
- wolfssh/internal.h
1. Add an error code and string for the message filtering fail.
2. Add a function to check incoming message IDs for appropriateness during the client or server handshake.
(ZD 17710)
> Messaging Filtering

- src/internal.c
1. Split ParseAndVerifyCert() into ParseCertChainVerify() and ParseCert() with a common ParseCertChain() function.
2. When the server is checking the user's certificate, don't do the verify step. Verify when the user's client sends a signature. The server needs to tell the client the cert is OK as a cert. Make the client do a PK sign.
3. If the certificate check fails, we still need to be able to send the failure message to the peer. Set the `ret` value back to `WS_SUCCESS`. All other auth actions are gated on the `authFailed`.
4. Whitespace.
(ZD 17555)
> Certificate OK

- .github/workflows/macos-check.yml
1. In the brew install step explicitly install autoconf and add libtool.
2. Skip running autogen.sh for wolfSSH, just use autoreconf directly.
3. Use "--enable-wolfssh" when building wolfSSL.
> macOS Action Update

- src/internal.c
Omit comma at the end when ssh->algoListKey is available.
ZD#17895
> Omit comma at the end

- src/internal.c
In `DoUserAuthRequestPublicKey` function there is a case in which `partialSuccess` is returned by the auth callback. When a public key passes the signature test and the auth result callback, the state of the authentication state machine gets set to `CLIENT_USERAUTH_DONE` even in case `partialSuccess` were to be true.
Fixes zd17917
> Fix state in DoUserAuthRequestPublicKey

- examples/client/client.c
- examples/client/common.c
- examples/client/common.h
- examples/echoserver/echoserver.c
- examples/scpclient/scpclient.c
- examples/sftpclient/sftpclient.c
- src/internal.c
Update wolfSSH to use wolfCrypt's static memory allocation pools. Most of wolfSSH already passes around a heap value that is passed into the WOLFSSH_CTX as a NULL. The echoserver and sftpclient examples have been updated with static pool descriptors that work on macOS and Linux builds when only SFTP is available. Some other changes were made in the client common code to include a heap when loading keys, and the other clients were updated for this.
(Fixes 17726)
> Static Memory Pools

- src/internal.c
- wolfssh/internal.h
1. Found some issues in some of the compiler guards for the key agreement functions.
2. Broke the key agreement out into separate functions to make the jumbo Kex functions a little smaller.
3. Added a ForceZero() for the Ecdh/Kyber shared secret.
4. Made explicit flags for all the kex types and check for them specifically. Fixes a miss in some Ecdh cases.
This should fix issue #678 and #679. This supercedes pull request #684.
> Key Agree Update

- src/wolfsftp.c
Make wolfSSH_SFTPNAME_readdir defining SFTP_Name_readdir. It has to be defined as a macro, but it can be defined to expand to its own name if also a function with the same name is defined.
What matters is that it takes 3 arguments:
1. the filesystem context as first argument
2. WDIR* as second argument
3. WS_SFTPNAME* as third argument
On successful execution, it returns WS_SUCCESS and the WS_SFTPNAME structure pointed by the third argument will be filled with the relevant info, otherwise a WS_* error code is returned.
This supersedes PR #552.
> ReadDir Override

- src/internal.c
1. Update the guards around the strings used to make the cannedKeyAlgoNames. If any algorithm is disabled, leave it out of the list. (I'm looking at you Ed25519!)
2. Added comments to those guards.
3. Reflow the alignment.
./configure --enable-wolfssh --enable-cryptonly && make clean && make
sudo make install
./configure --enable-debug && make clean && make
./examples/client/client -u $USER -p 22
For the failure case, this client connection attempt should indicate a -1051 error occurred.
> Guards Update: cannedKeyAlgoNames

- examples/echoserver/echoserver.c
- src/internal.c
- src/ssh.c
- wolfssh/internal.h
- wolfssh/ssh.h
Replaces https://github.com/wolfSSL/wolfssh/pull/544
> Key completion callback

- ide/Espressif/ESP-IDF/examples/wolfssh_echoserver/README.md
- ide/Espressif/ESP-IDF/examples/wolfssh_echoserver/components/wolfssl/CMakeLists.txt
- ide/Espressif/ESP-IDF/examples/wolfssh_echoserver/main/include/echoserver.h
- ide/Espressif/ESP-IDF/examples/wolfssh_echoserver/main/main.c
- ide/Espressif/ESP-IDF/examples/wolfssh_template/components/wolfssl/CMakeLists.txt
- wolfssh/test.h
Although it is already closed, this PR addresses https://github.com/wolfSSL/wolfssh/issues/697 and updates the published Espressif [wolfSSH Managed Component](https://components.espressif.com/components/wolfssl/wolfssh/). 
See the wolfSSL `scripts` for publishing details. I'll reference this PR when I submit the updates there.
There was an interim update of wolfSSL that had a _test_ but not a _fix_ for interleaved HW/SW that could under certain circumstances be problematic for both SSH and SRP. This was fixed in https://github.com/wolfSSL/wolfssl/pull/7535 and https://github.com/wolfSSL/wolfssl/pull/7505.
Once updated after the 5.7.0 wolfSSL release, the [wolfSSL Managed Component](https://components.espressif.com/components?q=namespace:wolfssl) needed to be updated as well.
There's a new …
> Update Espressif examples for Managed Component publish

- scripts/scp.test
- src/wolfscp.c
Before this change wolfssh's scp tries go into the send confirmation state when failing to open the local file.
ZD 18029
> error out when trying to send non existent local files

- src/internal.c
sha1 is only enabled when user intentionally enables NO_SHA1_SOFT_DISABLE
ZD#17793
> Enable sha1 when WOLFSSH_NO_SHA1_SOFT_DISABLE is enabled

- src/internal.c
- wolfssh/internal.h
1. Add a check for wc_RsaPrivateKeyDecodeRaw() to configure.
2. If wc_RsaPrivateKeyDecodeRaw() is available (from PR https://github.com/wolfSSL/wolfssl/pull/7608), use it to load the private key from GetOpenSshKeyRsa(). If unavailable, process the key the original way.
> Using Decode Raw RSA Private Key

- src/internal.c
1. Fix the typecasting when signing H with RSA.
2. Assign the sign return value to ret, then assign it to *sigSz if successful.
3. Similar change for the encoded sign value.
> Sign H Casting

- apps/wolfssh/wolfssh.c
- apps/wolfsshd/wolfsshd.c
- examples/client/client.c
- examples/portfwd/portfwd.c
- examples/scpclient/scpclient.c
- examples/sftpclient/sftpclient.c
- tests/api.c
- wolfssh/test.h
> improvements for ipv6

- src/wolfsftp.c
https://wolfssl.zendesk.com/agent/tickets/17964
Issue:
wolfSSH_SFTP_STAT doesn't check the server connection in it. 
If it is disconnected after wolfSSH_connect, the API alone doesn't detect
the disconnection and return WS_SUCCESS.
The issue is only the case wolfSSH_SFTP_STAT alone is used. sftpclient uses  wolfSSH_SFTP_STAT
with stream read/write so it detects the missing connection.
> connection check on wolfSSH_SFTP_STAT

- src/internal.c
For a Zephyr build setup, the compiler was complaining about some uninitialized variables that were getting used. Set them to 0 or NULL to make the compiler happy.
> Fix Initialization Warnings

- .github/workflows/singlethread-check.yml
- apps/wolfssh/wolfssh.c
- tests/api.c
- tests/sftp.c
- tests/testsuite.c
Fixes issues when wolfSSL is configured with `--enable-singletthreaded`
Also added workflow to test single thread build.
Reproduce with 
```
./configure --enable-wolfssh  --enable-singlethreaded --enable-keygen
```
```
./configure --enable-all
```
Fixes issue reported in https://www.wolfssl.com/forums/topic2133-how-to-compile-wolfssh-without-multithreading.html
> Fix testsuite with singlethreaded

- src/internal.c
- src/ssh.c
- wolfssh/internal.h
- wolfssh/ssh.h
Add a set of callback function hooks for various steps in the creation of a channel. These include:
* Channel Open
* Channel Open Confirm
* Channel Open Failure
* Channel EOF
* Channel Close
* Channel Request Shell
* Channel Request Subsystem
* Channel Request Exec
A channel request can be rejected by the request callbacks. Also added functions to query a channel's connection type and exec command.
> Channel Callbacks

- src/internal.c
- src/wolfscp.c
wolfSCP allocates a few buffers as needed and frees them immediately when done. It also checks at shutdown if the buffers need to be freed and frees them. When copying a large file (sink action), it will alloc and free the file buffer for each chunk of file sent by the peer. This could lead to fragmentation. Change the file receive and command buffers to be allocated when needed, and don't free them until cleanup.
```
./examples/scpclient/wolfscp -u john -i ~/.ssh/id_ecdsa -j ~/.ssh/id_ecdsa.pub -S $PWD/configure:$HOME/configure -p 22
sha256sum configure ~/configure
```
> Reduce SCP Allocations

- apps/wolfsshd/wolfsshd.c
Improvements to wolfSSHd to shutdown the connection cleaner, without disconnection errors. The server will keep processing the channel data and close its side of the connection. On socket shutdown, it will `shutdown` its side of the socket and read data from the socket until 0 return, then it closes the socket. Will also interrupt the child process if there are any socket errors.
(ZD 17722)
> wolfSSHd Connection Closure

- apps/wolfsshd/configuration.c
- apps/wolfsshd/wolfsshd.c
- src/internal.c
Add support for loading banner files into wolfSSHd. (ZD 18156)
Add "Banner filename.txt" to the sshd_config file used by wolfSSHd.
> SSHD Banners

- src/internal.c
Rearrange the matching of the MAC Algos when decoding the KEX Init message. It should only dereference the handshake info to check if it is using an AEAD cipher if ret is WS_SUCCESS. (If the handshake info isn't present, there will be an error present.) This prevents a possible NULL dereference.
> Fix MAC Algo Match

- apps/wolfsshd/wolfsshd.c
ZD 18152
This fixes the case where the command:
`./examples/client/client -u Fred -h 192.168.0.X -Ppassword -c dir > stdout.txt` would result in virtual terminal characters placed in stdout.txt.
It also avoid virtual terminal characters placed in bash variables.
> Fixes for SSHD Windows virtual terminal sequences

- src/wolfscp.c
- wolfssh/internal.h
1. Splitting the top level SCP functions for either from or to, and incorporating the sub-functions in appropriately.
2. Put making the scp command line to send to the peer into its own function.
> Nonblocking SCP

- ChangeLog.md
- src/internal.c
Need to use the old RSA key read function if using FIPS wolfCrypt.
> Release v1.4.18: Release Fixes

- ide/Espressif/ESP-IDF/examples/wolfssh_echoserver/main/include/main.h
- ide/Espressif/ESP-IDF/examples/wolfssh_echoserver/main/include/time_helper.h
- ide/Espressif/ESP-IDF/examples/wolfssh_echoserver/main/main.c
- ide/Espressif/ESP-IDF/examples/wolfssh_echoserver/main/time_helper.c
This PR addresses the Espressif `wolfssl_echoserver` build error noted in https://github.com/wolfSSL/wolfssh/issues/728 when publishing wolfssh as a Managed Component by updating the example and not the library. The root cause of the problem is the [un-gated header timelib functions](https://github.com/wolfSSL/wolfssl/blob/7c6eb7c4a1c9b933b35f4de38b7310b663516a69/wolfssl/wolfcrypt/port/Espressif/esp-sdk-lib.h#L152) and the respective type difference: `int` vs `esp_err_t`.
Eventually the example needs to be revised to completely remove the local timelib and use the [esp-sdk-lib.h](https://github.com/wolfSSL/wolfssl/blob/master/wolfssl/wolfcrypt/port/Espressif/esp-sdk-lib.h) instead.
For now, since both the local example code and the `esp-sdk-lib.h` use the same time-related function names, …
> Adjust Espressif wolfssl_echoserver example timehelper

- src/internal.c
- wolfssh/error.h
- wolfssh/internal.h
- zephyr/samples/tests/wolfssl_user_settings.h
- zephyr/samples/tests/wolfssl_user_settings_nofs.h
Switching to use the new SSH-KDF function in wolfCrypt. Note, this only works in FIPS builds and/or when Kyber isn't used.
> Use wolfCrypt SSHv2 KDF

- apps/wolfsshd/test/README.md
- apps/wolfsshd/test/run_all_sshd_tests.sh
- apps/wolfsshd/test/sshd_window_full_test.sh
- apps/wolfsshd/wolfsshd.c
- examples/client/common.c
> cat of large file with ssh shell

- apps/wolfssh/wolfssh.c
> continue to cleanup on fail case and use WLOG for debug messages

- src/internal.c
The function HashForId() was declared as INLINE. Remove it. The function is getting exported as WOLFSSH_LOCAL which conflicts with the inline.
(ZD 18448)
> Remove Inline

- apps/wolfssh/wolfssh.c
- apps/wolfsshd/wolfsshd.c
- examples/client/client.c
- examples/echoserver/echoserver.c
- examples/portfwd/portfwd.c
- examples/scpclient/scpclient.c
- examples/sftpclient/sftpclient.c
Updates apps to display the version of wolfSSL compiled with:
```
$ ./apps/wolfsshd/wolfsshd -v
wolfSSHd 1.4.18 linked with wolfSSL 5.7.2
-?             display this help and exit
-f <file name> Configuration file to use, default is /etc/ssh/sshd_config
-p <int>       Port number to listen on
-d             Turn on debug mode
-D             Run in foreground (do not detach)
-h <file name> host private key file to use
-E <file name> append to log file
```
> show version of wolfSSL linked to

- src/internal.c
- src/wolfscp.c
> static analysis report review

- apps/wolfsshd/test/run_all_sshd_tests.sh
- apps/wolfsshd/test/sshd_bad_sftp_test.sh
- src/internal.c
- src/ssh.c
- src/wolfsftp.c
- wolfssh/internal.h
- wolfssh/port.h
ZD 18566
Fix for SFTP cases with trailing delimiter.
OpenSSH client 9.6 (which does a SFTP command instead of SCP, -O restores using SCP protocol)
```
mkdir /tmp/subfolder
scp /tmp/test.txt jill@127.0.0.1:/tmp/subfolder/test/
```
Before this change wolfSSH would allow test.txt to be copied to /tmp/subfolder/test. After this change the command correctly fails.
> keep trailing delimiter with SFTP open

- apps/wolfsshd/test/run_all_sshd_tests.sh
- apps/wolfsshd/test/sshd_term_close_test.sh
- apps/wolfsshd/wolfsshd.c
> kill child process after SSH connection failure

- .github/workflows/zephyr.yml
The v3 support was removed on 2025-01-30, it no longer works.
> Fix GitHub Actions upload artifact

- .github/workflows/scp-test.yml
- src/wolfscp.c
> SCP hang with interop fix

- .github/workflows/sshd-test.yml
- apps/wolfsshd/test/run_all_sshd_tests.sh
- apps/wolfsshd/test/ssh_kex_algos.sh
- src/internal.c
- wolfssh/internal.h
ZD19314
Also refactored the SSHD test script to accommodate running a specific test and added check for HAVE_ALL_CURVES macro when determining if P384/P521 is available.
> Add back in P521 and P384 by default when enabled

- src/internal.c
- src/wolfscp.c
- wolfssh/internal.h
ZD19249
We should not be attempting any modification on a const char* buffer. This sets it to always be dynamic.
> use dynamic buffer for SCP base path

- wolfssh/internal.h
Found when compiling with `wolfSSL` built with `--enable-opensslcoexist` it will lead to compile errors like:
```
| ../git/wolfssh/internal.h:462:27: error: 'AES_BLOCK_SIZE' undeclared here (not in a function); did you mean 'WC_AES_BLOCK_SIZE'?
|   462 | #define STATIC_BUFFER_LEN AES_BLOCK_SIZE
|       |                           ^~~~~~~~~~~~~~
| ../git/wolfssh/internal.h:475:31: note: in expansion of macro 'STATIC_BUFFER_LEN'
|   475 |     ALIGN16 byte staticBuffer[STATIC_BUFFER_LEN];
```
Found this issue when trying to make a yocto image that has `wolfSSL`, `wolfSSH`, and `wolfProvider`. wolfProvider needs opensslcoexist according to documentation.
> Adding define for wc_aes_block_size

- .github/workflows/cppcheck.yml
- apps/wolfsshd/auth.c
- examples/portfwd/portfwd.c
- ide/Renesas/cs+/demo_server/wolfssh_demo.c
- src/agent.c
- src/internal.c
- src/port.c
- src/ssh.c
- src/wolfsftp.c
Found and fixed:
* Fix typos in Renesas demo
* Fix uninitialized variable reads
* Fix redundant condition in wolfsshd
* Fix argument checks in wolfsshd
* Fix some null ptr dereferences
* Fix ambiguous statement
> Add cppcheck test to GitHub actions

- apps/wolfssh/wolfssh.c
If the client is not provided a hostname, `ClientPublicKeyCheck` would crash trying to match `targetName`. A hostname is required.
> Fix crash when client has no hostname

- apps/wolfsshd/test/run_all_sshd_tests.sh
- apps/wolfsshd/test/sshd_scp_fail.sh
- examples/scpclient/scpclient.c
- src/wolfscp.c
SCP on the server side would get an EAGAIN around the 128KB mark, which would trigger an error. That error in-turn would cause two attempts to close the file, which would segfault.
Also fix inverted error return status on scpclient.
> Fix SCP server side

- .github/workflows/sshd-test.yml
- apps/wolfsshd/wolfsshd.c
https://github.com/wolfSSL/wolfssh/issues/772
> fix for FD_SET call on pipes and handling of channel EOF

- src/wolfsftp.c
When connecting to the wolfSSH SFTP server, running the command `ls -l` shows all regular files as symlinks. This patch fixes the check for files being symlinks or not and update their indication in the longname.
(ZD 19554)
> Fix SFTP Symlink Indication

- .github/workflows/kyber.yml
- README.md
- src/internal.c
- src/ssh.c
- wolfssh/internal.h
> Replace Kyber 512 with ML-KEM 768.

- examples/echoserver/echoserver.c
> Forgive a socket error

- wolfssh/port.h
Triggered on a customer's FATFS build with -Werror.
> Fix warning on FATFS builds

- README.md
Minor spelling edits, encountered in scripts.
> spelling edits

- src/internal.c
- tests/auth.c
* `keyboardAuthCb` was not initalized correctly, meaning we could enable the mode without callback.
* `SendUserAuthKeyboardRequest` didn't check `keyboardAuthCb` for `NULL`.
* `DoUserAuthInfoResponse` left `authData` partially uninitialized.
* `DoUserAuthInfoResponse` new checks that KB auth is in progress.
> Keyboard Interactive bug fixes

- examples/client/client.c
- src/internal.c
- tests/kex.c
1. By default, soft disable AES-CBC. It isn't offered as a default encrypt algorithm, but may be set at runtime.
2. Add guard where AES-CBC can be added back as a default.
3. Add option to example client to run it with a custom encrypt algorithm list.
4. In the client, add macro to add items to the arg lists while checking the number of items in the list.
(ZD 19606)
> Soft Disable AES-CBC

- examples/echoserver/echoserver.c
- scripts/sftp.test
- src/internal.c
> adjust highwater check location to avoid masking return value 

- wolfssh/test.h
Related to my upcoming Espressif changes: the old threading functions, when enabled, encounter a compile-time error if `SINGLE_THREADED` is enabled.
See also https://github.com/wolfSSL/wolfssh/pull/770, pulled out here as a separate topic.
> Disable old threading functions when SINGLE_THREADED

- src/ssh.c
Updates `ssh.c` to fix compile-time error when RSA is disabled.
Without this fix, this line in `DoAsn1Key()`:
```
ret = wc_RsaFlattenPublicKey(&key->ks.rsa.key, (byte*)&e, &eSz, n, &nSz);
```
fails to compile as there's no `.rsa.key` member property:
```
Severity Description                                   Project                File                                         Line
Error    'union <anonymous>' has no member named 'rsa' wolfssl_IDF_v5.2_ESP32 C:\workspace\wolfssh-master-update\src\ssh.c 1751
```
With this  PR, the code compiles and exits `IdentifyAsn1Key()` with error code `WS_RSA_E` and a message when debugging is enabled.
> DoAsn1Key now fails when WOLFSSH_NO_RSA is defined

- src/internal.c
- src/ssh.c
- src/wolfscp.c
- src/wolfsftp.c
- wolfssh/port.h
1. Remove the macro definition and checks for the value "NO_BREAK".
2. Use the wolfCrypt defined macro FALL_THROUGH instead of NO_BREAK.
> Change switch fallthrough

- apps/wolfssh/common.c
- apps/wolfsshd/wolfsshd.c
- examples/client/common.c
- examples/sftpclient/sftpclient.c
- src/ssh.c
- tests/api.c
1. String not null terminated: 572834
2. Dereference before null check: 572919 572847
3. Buffer not null terminated: 572891
4. Argument cannot be negative: 573009 572928 572868
> Fixing a batch of issues reported by Coverity

- Makefile.am
- configure.ac
1. In the automake scripts, remove unused variables.
2. Update the required tool version numbers in configure.ac to the versions available at the time wolfSSH was first put together.
3. Consolidate the enabled option checks.
> Autoconf and Automake Updates

- src/internal.c
Adds NULL checks to clear Coverity issues reported in ZD#20212.
- Dereference before NULL check
- check `ssh->ctx != NULL` before dereferencing in `GetAllowedAuth()` (wolfSSH Project **572900**)
- Dereference after NULL check
- Add additional NULL checks as `SendUserAuthKeyboardRequest()` does not return immediately if `ssh` or `authData` are NULL (wolfSSH Project **CI 572871** and **CI 572874**)
- `AlgoListSz()` returns 0 if param is NULL (wolfSSH Project **572893**)
> Zendesk Coverity changes

- src/internal.c
- wolfssh/internal.h
> only send ext info once after SSH_MSG_NEWKEYS

- src/internal.c
- src/ssh.c
- wolfssh/internal.h
- wolfssh/ssh.h
1. For the Query name by index functions, rename `index` as `idx`. Some versions of the C library have a global named `index` that can get shadowed.
2. Fix some whitespace.
(ZD#20321)
> Fix Shadowed Index

- src/ssh.c
> Rename struct Buffer to WOLFSSH_BUFFER in wolfSSH_ShowSizes to match previous rename.

- src/wolfsftp.c
> additional sanity checks on SFTP handle size
