wolfSSL/wolfssh

src/internal.c

More proper return code and length checking.

More Cleanup

---

src/internal.c

Fixed a missed set of wolfCrypt functions whose return values weren't getting checked.

wolfCrypt Fix

---

src/internal.c
wolfssh/internal.h

Add function to send Channel Success and Failure to the client when receiving Channel Request messages, when requested.

Channel Success Message

---

examples/echoserver/echoserver.c
src/internal.c
src/ssh.c
wolfssh/internal.h
wolfssh/ssh.h

Removed the canned banner and added a way to provide your own banner.

Update the banner

---

src/internal.c

Added a check for the size of the destination buffer in GetString().

Fix GetString

---

examples/echoserver/echoserver.c
src/ssh.c
wolfssh/ssh.h

Added a control key reaction to the echoserver so that it dumps out some session statistics. (bytes transmit, bytes received, current transmit sequence number, current receive sequence number) "Ctrl-E" will show the statistics in both the ssh client and in the echoserver.

Echoserver Enhancement

---

examples/client/client.c
examples/echoserver/echoserver.c
examples/server/server.c
gencertbuf.pl

gencertbuf.pl is based off of the wolfSSL version of it

use of buffer keys in examples with no filesystem

---

src/internal.c

revert code to allow RSA connection.
./examples/client/client -p 22 -h test.rebex.net -u demo

revert increment of nameListIdx for RSA connection

---

README.md

The correct configure option is --enable-ssh
Thanks!

changed configure option for building wolfSSL per John S. comments

---

configure.ac
wolfssh/version.h

bump dev version to 1.2.2

---

examples/client/client.c
src/internal.c
src/ssh.c
src/wolfsftp.c
tests/unit.c
wolfsftp/client/sftpclient.c

Ran the clang static analysis and infer and fixed most of the reported items. There were many that infer found that looked like false positives.

Static Analysis Fixes

---

examples/client/client.c
examples/server/server.c
src/internal.c
wolfssh/test.h

1. Added a fix for the use of non-blocking sockets.
2. Added support to the example client that uses non-blocking.

Non-blocking Fix

---

ide/winvs/include.am
ide/winvs/wolfsftp-client/wolfsftp-client.vcxproj
ide/winvs/wolfsftp-client/wolfsftp-client.vcxproj.user
ide/winvs/wolfssh.sln
ide/winvs/wolfssh/wolfssh.vcxproj
src/internal.c
src/port.c
src/wolfscp.c
src/wolfsftp.c
tests/api.c
wolfsftp/client/sftpclient.c
wolfssh/port.h
wolfssh/settings.h

1. Add support for SFTP for Windows.
2. Add a client for SFTP for Windows.
3. Add a new strcat function that requires the destination's length.

SFTP for Windows

---

src/internal.c
src/misc.c
wolfssh/misc.h

Fix for an intermittent connection fail case when leading 0's are in the shared secret.

check on mpint shared secret

---

configure.ac
examples/client/include.am
examples/echoserver/include.am
examples/server/include.am

1. Add a disable for the example tools to configure.
2. Add a disable for the client side code to configure.
3. Add a disable for the server side code to configure.

Configure Update

---

src/internal.c

The callback was getting a pointer to the raw public key data in the receive buffer including the blob length, this caused the pubkey to be short in the callback. Updated the pubKey given to the callback to be the SSH encoded blob without the total size, and pass the total size in. Also, update the hash of the public key to include the size.

Server Public Key Bug Fix

---

configure.ac
gencertbuf.pl

Updated the gencertbuf.sh script and configure.ac.

Update the copyright to 2019

---

src/wolfscp.c
src/wolfsftp.c

For https://github.com/wolfSSL/wolfssh/issues/159

fix for gcc 8 build warnings

---

ide/Renesas/cs+/README.md
ide/Renesas/cs+/README_jp.md
ide/Renesas/cs+/common/strings.h
ide/Renesas/cs+/common/unistd.h
ide/Renesas/cs+/common/user_settings.h
ide/Renesas/cs+/common/wolfssh_csplus_usersettings.h
ide/Renesas/cs+/demo_server/demo_server.mtpj
ide/Renesas/cs+/demo_server/wolfssh_demo.c
ide/Renesas/cs+/demo_server/wolfssh_demo.h
ide/Renesas/cs+/demo_server/wolfssh_dummy.c
ide/Renesas/cs+/wolfssh_lib/wolfssh_lib.mtpj
ide/Renesas/cs+/wolfssl_lib/wolfssl_lib.mtpj
ide/include.am
src/internal.c
src/ssh.c
wolfssh/port.h

Added example ssh server under renesas CS+ and alpha project
Fixed CC-RX compiler warnings

Add example ssh server code for renesas CS+

---

examples/client/client.c
examples/echoserver/echoserver.c
src/internal.c
src/io.c
src/ssh.c
wolfssh/internal.h
wolfssh/ssh.h

Global request

---

src/internal.c

Found using cppcheck. Also fixed debug logging getting missed from my
previous PR.

More NULL ptr dereference fixes

---

src/wolfsftp.c

Thanks to @LinuxJedi for the report here https://github.com/wolfSSL/wolfssh/issues/179.

fix check on want write state with SFTP

---

src/wolfsftp.c
wolfssh/wolfsftp.h

Fixes in comments and debug print outs for the issues:
https://github.com/wolfSSL/wolfssh/issues/185
https://github.com/wolfSSL/wolfssh/issues/187
https://github.com/wolfSSL/wolfssh/issues/167

fix comments and add in more

---

src/wolfsftp.c

for issue https://github.com/wolfSSL/wolfssh/issues/191

update comment on SFTP name list free function

---

src/internal.c
src/wolfscp.c
wolfssh/internal.h

interop with pscp -scp type commands

fix for pscp interop

---

.gitignore
examples/sftpclient/sftpclient.c
scripts/get-put.test
scripts/include.am
src/wolfsftp.c

1. Add an SFTP automated test.
2. Update wolfSSH_SFTP_STAT() with clearing the error register if it is WANT_READ.

Automatic Client Test

---

examples/echoserver/echoserver.c
ide/winvs/api-test/api-test.vcxproj
src/internal.c
src/wolfsftp.c

Fixes for issues found during the release testing.

Release fixes

---

configure.ac
src/port.c
src/wolfsftp.c

for Issue https://github.com/wolfSSL/wolfssh/issues/221

use off_t type with pwrite/pread

---

src/wolfscp.c
src/wolfsftp.c

reported at https://github.com/wolfSSL/wolfssh/issues/221, thanks @guidovranken

clean up clang compile warnings

---

src/internal.c

ZD 9638
ZD 9639
ZD 9640
ZD 9643

additional sanity checks

---

examples/sftpclient/sftpclient.c
src/internal.c
src/ssh.c
tests/testsuite.c
wolfssh/error.h
wolfssh/internal.h

Allow user callback to decide if password or public key https://github.com/wolfSSL/wolfssh/issues/233

public key vs password is now decision of user callback

---

src/internal.c

AES-CTR encrypt is supposed to work when the input and output pointers are the same. The FIPSv2 version of the function doesn't work this way, it only works when the input and output are different. This commit adds a helper function that wraps the AES-CTR encrypt function when using
FIPSv2 so it only encrypts/decrypts a single block at a time.

AES-CTR Fix

---

examples/client/client.c
examples/sftpclient/sftpclient.c
src/internal.c
src/ssh.c
tests/api.c
wolfssh/certs_test.h
wolfssh/port.h
wolfssh/ssh.h
wolfssh/test.h

Also includes some bug fixes.
1. Add a function that returns a pointer to a session's username string.
2. Add a function to set a "raw" username copied from an incoming packet.
3. Add tests for 1 and 2.
4. Server saves a copy of the username on successful authentication.
5. Fix bug with GetString() where it would choke on a 0 length string.
6. Clean up the termios macros and mode creation.
7. Add some options for when WOLFSSL_VXWORKS is set.

VxWorks Customizations

---

src/internal.c
src/wolfscp.c

remove mp_todecimal to fix sp build

---

examples/sftpclient/sftpclient.c
src/wolfsftp.c

fix XFREE/MALLOC typo to be WFREE/MALLOC

---

src/internal.c

For issue https://github.com/wolfSSL/wolfssh/issues/245

init on mp_int r and s

---

src/internal.c

Added the ability to the client to authenticate to a server using an ECC key or RSA key. The server will pick the one it'll use. The client announces it can handle both ssh-rsa and ecdsa-sha2-nistp256 certificates from the server.

ECC Server Authentication

---

src/internal.c

add free of buffer to GetStringAlloc

---

src/internal.c

initialize list values

---

src/internal.c
wolfssh/internal.h

1. Added checking to see if the client's DH Init message is a guess or not and if not, skip it if a kex message follows.
2. Added some strings for some other KEX methods.

Dropbear Interoperation Improvement

---

README
README.md
configure.ac
examples/echoserver/echoserver.c
tests/testsuite.c

Add support to the echoserver for spawning a shell when a user connects.

Shell Worker

---

src/internal.c

add sanity check on amount requested to be sent

---

src/wolfsftp.c

fix for non blocking interop with winscp

---

src/internal.c

1. Increase the size of the processed ID list from the peer from 8 to 16. (ZD 9820)

Fix ID List

---

examples/client/client.h
examples/echoserver/echoserver.h
examples/portfwd/wolfssh_portfwd.h
examples/scpclient/scpclient.h
examples/server/server.h
examples/sftpclient/sftpclient.h
wolfssh/agent.h
wolfssh/certs_test.h
wolfssh/error.h
wolfssh/internal.h
wolfssh/keygen.h
wolfssh/log.h
wolfssh/misc.h
wolfssh/port.h
wolfssh/settings.h
wolfssh/ssh.h
wolfssh/test.h
wolfssh/version.h
wolfssh/version.h.in
wolfssh/visibility.h
wolfssh/wolfscp.h
wolfssh/wolfsftp.h

Change file including guard from pragma-once to ifndef-define. This follows the pattern from our other projects.

Include File Guards

---

examples/sftpclient/sftpclient.c

add example timeout to sftp example

---

examples/echoserver/echoserver.c

add peek when waiting for data

---

examples/echoserver/echoserver.c
wolfssh/port.h
wolfssh/test.h

skip WOLFSSH_TEST_SERVER, WOLFSSH_TEST_ECHOSERVER over test.h
need WS_SELECT_RECV_READY

minor fix for MQX

---

src/internal.c
src/wolfscp.c
src/wolfsftp.c
tests/sftp.c
wolfssh/internal.h

add special case for real path and refactor clean_path

---

examples/echoserver/echoserver.c

1. Remove calls to wc_Sha256 Init, Update, and Final and remove the instances of the wc_Sha256 structure.
2. Remove the c32toa function, it isn't used at this point.
3. Add calls to wc_Sha256Hash().
This removes the Sha256 structure off the stack and replaces it with the direct call to the single-shot hash routine. Flattening the size of the hashed data and hashing it in was removed as redundant.

Hide SHA from Echoserver

---

ide/MQX/Makefile
ide/MQX/README-jp.md
ide/MQX/README.md
ide/MQX/include.am
ide/include.am

add ide/MQX

---

src/internal.c

Resolves OSS-Fuzz issue 27666 (see ZD 11429)

Use overflow-safe bounds checking in DoKexDhReply

---

examples/sftpclient/sftpclient.c
src/internal.c

Resolves OSS-Fuzz issue 27436 (see ZD 11429)

Fix memmove length calculation in wolfSSH_CleanPath

---

src/ssh.c

Resolves OSS-Fuzz issue 27298 (see ZD 11429)

Use WSTRNCMP for comparing session command string

---

src/wolfsftp.c

close local file on error case

---

src/wolfscp.c

In ReceiveScpConfirmation reserve room for NULL-terminator.

---

examples/echoserver/echoserver.c
src/agent.c
src/internal.c
src/ssh.c
tests/api.c
wolfssh/internal.h

1. Added general disable flags for RSA and ECDSA.
2. Replaced HAVE_ECC, NO_RSA, NO_DSA with the general disable flags.

More Options

---

src/internal.c

1. When processing public key user auth, use GetSize() instead of GetUint32(). (ZD 11654 and 11655)
2. When processing public key user auth, initialize the key earlier.

Fuzz Fixes

---

src/internal.c

Add function to purge a packet in case building one fails.

PurgePacket

---

src/wolfsftp.c

fix for cleanup in error case

---

src/internal.c

reset kSz for rekey fix

---

src/wolfsftp.c
wolfssh/port.h

This PR adds support for [ChaN's FatFs](http://elm-chan.org/fsw/ff/00index_e.html).

Added support for FatFs

---

ide/IAR-EWARM/Projects/README.md
ide/IAR-EWARM/include.am

Add README and remove test_user_io.h from include.am

Add README.md under IAR-EWARM/Projects, fix include.am

---

src/internal.c
src/misc.c

1. Fixed a leak.
2. Fixed a branch on uninitialized.
(ZD 12640 and 12642)

Fuzzing Fixes

---

src/wolfsftp.c

When decoding SFTP messages, fix the size checks so they don't wrap. (ZD12766)

ASAN SFTP Fixes

---

src/ssh.c
wolfssh/port.h

fix for typo and reduce stack size

---

src/wolfscp.c

When scp receives a string in STDERR, print it out, rather than treating it as an error.

wolfSCP and STDERR

---

src/ssh.c

1. Refactor wolfSSH_ChannelRead() and wolfSSH_ChannelIdRead() to use the same receive function.
2. Add window updates to the channel read internal function.

Window Adjust Fix

---

src/internal.c

fix check on RSA import size

---

src/internal.c

small stack optimizations

---

src/internal.c

Remove a redundant free of a hash object. The hash itself it still being updated and will be freed later.

Remove redundant free

---

src/wolfsftp.c

fix handling sent data sz when its size is greater than peer max packet size

---

src/agent.c
tests/api.c

* Fixes for building without RSA or ECC.
ZD 12663

Fixes for use with KCAPI

---

src/internal.c
src/wolfsftp.c
wolfssh/error.h

https://wolfssl.zendesk.com/agent/tickets/13769

Missing return value

---

src/internal.c
src/ssh.c
tests/testsuite.c

* Fix for building against wolfCrypt FIPS 140-2 and 140-3.

Fixes for building with FIPS

---

examples/client/client.c
examples/echoserver/echoserver.c
examples/echoserver/include.am
examples/portfwd/portfwd.c
examples/scpclient/scpclient.c
examples/server/server.c
examples/sftpclient/sftpclient.c
src/agent.c
src/keygen.c
wolfssh/internal.h

Add preprocessor guards for RSA/ECC to agent and the example and test applications.

Preprocessor Guards

---

src/internal.c

this replaces https://github.com/wolfSSL/wolfssh/pull/403 after it ended up a mess
addresses https://github.com/wolfSSL/wolfssh/issues/402

initialize pointers to NULL, others to zero

---

src/keygen.c
tests/include.am
tests/unit.c
wolfssh/keygen.h

1. Added a wrapper function for ECDSA key generation like the RSA key generation.
2. Added keygen to the unit test.

Add ECDSA Key Generation Wrapper

---

README.md
configure.ac
src/internal.c
wolfssh/internal.h

Tested with the following: 
./autogen.sh 
./configure --enable-liboqs
make all check 
Also tested for interop with OQS fork of libssh. See README.md for instructions.

SABER Level 1 Support in wolfSSH

---

ChangeLog.md

Move vulnerability to it's own section in changelog with attribute to researcher

---

src/internal.c
src/wolfscp.c

ZD14337
Fix for wolfSSH SCP client interop issue with newer versions of OpenSSH (8.3+ reported) server due to the server sending extended data.

handle extended data with scp connection

---

examples/echoserver/echoserver.c
src/internal.c
src/ssh.c
src/wolfsftp.c

SFTP want write and SSH quick rekey issues

---

src/wolfsftp.c
wolfssh/internal.h

handle larger ext sizes with SFTP connect

---

examples/sftpclient/sftpclient.c

Resolves build issues in VS when `WOLFSSH_SFTP` is defined.

Add WIN time support in SFTP client

---

src/internal.c

fix amount copied when condensing string

---

src/ssh.c
tests/api.c
wolfssh/ssh.h

1. Add a function for returning a RealPath per the SFTP RFC.
2. Add a test function for the RealPath to test against.

SFTP RealPath

---

src/certman.c

sanity check on number of certs in chain

---

apps/wolfsshd/wolfsshd.c

1. Stash a copy of wolfsshd's listenFd in the connection record.
2. After the fork, the child now closes the listenFd.
3. After the fork, the parent now closes the fd.

Child Listener

---

src/internal.c

Fix wolfSSH client: freeing uninitialized data

---

apps/wolfsshd/wolfsshd.c

This clears the timeout mechanism used for the login grace timer on successful login.

Clear Alarm

---

examples/echoserver/echoserver.c
examples/echoserver/echoserver.h
tests/api.c
tests/testsuite.c
wolfssh/port.h
wolfssh/test.h

1. Whitespace.
2. Threading updates
3. Improve the consistency of the asserts().
4. Improve the echoserver test driver.
5. Tweaks for Integrity.

Test Threading

---

src/internal.c

adjustment for handling '/./' case

---

src/internal.c

1. Add guards around uses of algorithm names strings that shouldn't be included if the algo is disabled.
2. Add a little more context to the error strings in the cert versions of the signing functions.

ECDSA Signing Guards

---

ChangeLog.md
configure.ac
gencertbuf.pl
src/certman.c
wolfssh/certman.h
wolfssh/version.h

Just the usual first touches for a release. Version numbers, library version numbers, change logs, copyright dates.

Updates for new release v1.4.12

---

src/wolfsftp.c

1. Remove ununsed variable in a function for the Windows build.

Release Cleanup 2

---

examples/sftpclient/include.am
examples/sftpclient/sftpclient.c

Fix 32-bit builds of the SFTP client.  Only build SFTP client if building examples is enabled.

---

apps/wolfsshd/wolfsshd.c
examples/echoserver/echoserver.c
examples/sftpclient/sftpclient.c
src/internal.c
src/ssh.c
src/wolfsftp.c
tests/api.c
wolfssh/test.h

1. Made changes to the SFTP handling to improve working with LwIP.
2. Made changes to the SFTP handling to improve speed.
3. Updated echoserver, sftpclient, and wolfSSHd.

Updates for SFTP Support

---

examples/echoserver/echoserver.c
src/internal.c

1. Tighten up scope on variables in function SendKexDhReply.
2. Fix echoserver not handling the non-blocking would block state for SFTP.

Variable Scoping

---

apps/wolfsshd/wolfsshd.c
examples/echoserver/echoserver.c
examples/scpclient/scpclient.c
src/ssh.c
src/wolfscp.c

setup chroot with scp operations too, breaks after SSH handshake and returns to application

break between SSH accept and SCP operation

---

src/internal.c
wolfssh/internal.h

Fuzzing found an issue with the I/O buffer handling. This refactor simplifies the handling inside the existing functions. (ZD#16242)

Buffer Grow Fix

---

apps/wolfsshd/auth.c
apps/wolfsshd/wolfsshd.c

adjustment for cases where privileged access is needed for set and get group function calls

adjust set and get groups

---

apps/wolfsshd/wolfsshd.c
src/internal.c

Set the client sides window size low and leave the server side large to test.
Client side configure:
`./configure CPPFLAGS="-DDEFAULT_WINDOW_SZ=32600 -DWOLFSSH_NO_SFTP_TIMEOUT" --enable-all`
Server side configure running wolfSSHd
`./configure --enable-all`

better handling of window full cases and chroot with SFTP

---

apps/wolfsshd/configuration.c
src/internal.c

`./configure --enable-all CC=g++ && make`

fix warnings for g++ build

---

src/internal.c

account for partial send cases

---

apps/wolfsshd/wolfsshd.c

fix for report given by direct email

better handling of want read/write cases with SFTP + SSHD

---

src/wolfsftp.c
wolfssh/internal.h

make dir handle list local to WOLFSSH object

---

src/wolfsftp.c
wolfssh/internal.h

Added new state and related buffer. Should eventually be replicated for the client

Support partial packet reads during the SFTP server-side initialization.

---

src/internal.c

Fix for https://github.com/wolfSSL/wolfssh/issues/562

fix for dh group connections

---

src/internal.c

fix for SFTP interop

---

src/wolfsftp.c

Addresses comment from the pull request https://github.com/wolfSSL/wolfssh/pull/551

additional checks on packet size

---

src/internal.c

sanity check on first read with opcode

---

apps/wolfsshd/wolfsshd.c

keep permissions rasied when binding to socket

---

apps/wolfsshd/wolfsshd.c

Before this change even when just sending data there would still be a wait on 'select' which killed throughput performance.

fix speed of SFTP with SSHd when handling 'get' command

---

src/internal.c

Tentative fix for the #605 issue.

Fix for #605: check for WS_WANT_READ too.

---

src/log.c
wolfssh/port.h

handling large debug messages on Windows system report

truncate vsnprintf

---

src/wolfsftp.c

Fix for dirty read on Windows with SFTP.
ZD16961

do not require locking file with SFTP on Windows

---

apps/wolfsshd/test/run_all_sshd_tests.sh
apps/wolfsshd/test/sshd_login_grace_test.sh
apps/wolfsshd/wolfsshd.c

fix for grace period login and add test case

---

src/internal.c

Update the buffer's index in DoReceive() any time the buffer's index is updated in DoPacket().  

---

README.md

Manually tested and double checked the text.

Change references in README.md from John to Fred.

---

apps/wolfsshd/wolfsshd.c
src/internal.c

refactor windows wolfsshd service to resolve powershell Write-Progress

---

.github/workflows/kyber.yml

Add a workflow for a kyber testing. It's only a make check, but ECDSA+Kyber is the default KEX.

Kyber Testing

---

apps/wolfsshd/wolfsshd.c

Fix compile error triggered by enabling TEST_IPV6

---

examples/scpclient/scpclient.c
src/wolfscp.c

adjust scp error return checking for closed channels

---

examples/scpclient/scpclient.c
src/ssh.c

add check for channel closed error

---

src/internal.c
wolfssh/internal.h

Add DH Group 14 with SHA256 KEX support.

DH Group 14 with SHA256

---

examples/scpclient/scpclient.c
src/wolfscp.c

Scp example free memory on failure

---

.github/workflows/sshd-test.yml
apps/wolfsshd/wolfsshd.c

fix for handling memory on socket timeout

---

README.md

Not ML-DSA; ML-KEM

---

src/internal.c

https://github.com/wolfSSL/wolfssh/issues/759

update wolfSSL version listed in comment

---

src/wolfsftp.c

Fixed small typo: Attirbutes -> Attributes

Fixed typo

---

src/internal.c

Customer reported possible uninitialized usage
Fixes ZD 19809

Init a pointer to NULL
